// packages/solid/src/App.tsx
import { type Component, type ParentProps, ErrorBoundary, For, Show, createSignal } from "solid-js";
import { A, useLocation } from "@solidjs/router";
import { useTheme } from "./lib/theme";
import { NAV } from "./nav";
import ReleaseNotes from "./components/ReleaseNotes";
import { Search } from "./components/form/search/search";

/**
 * Derived from NAV, never hand-counted: nav.ts is already the single source of
 * truth for the sidebar and the landing catalogue, and a hard-coded number here
 * would drift the moment a component is added.
 *
 * Two exclusions, for two different reasons. `catalogue: false` groups (Getting
 * started) are routes rather than components. `components: false` groups
 * (Patterns) ARE on the landing page but are screens assembled from the
 * components above — counting them would count the same components twice.
 */
const COMPONENT_COUNT = NAV.filter((g) => g.catalogue !== false && g.components !== false).reduce(
  (n, g) => n + g.items.length,
  0,
);

/**
 * The root site, one level up from this demo's own base — derived, not "/".
 * The demo is mounted at /builder-solid/ under `dev:all` and at
 * /zen-ui/builder-solid/ on GH-Pages, and the way out has to land on the right
 * root in both. Hardcoding "/" would walk out of the deployment entirely.
 */
const ROOT_URL = new URL("..", new URL(import.meta.env.BASE_URL, window.location.origin))
  .pathname;

/**
 * "View code" opens the demo file for the route you are on — the USAGE, not the
 * component's internals. The page already prints a snippet, but that snippet is
 * a hand-typed `code` string sitting next to the JSX it claims to describe, and
 * nothing keeps the two honest. This is the file that actually ran.
 *
 * Pinned to `main` rather than the current branch: a link that only resolves on
 * whatever branch happened to build it is a link that breaks on every other one.
 * The paths come from nav.ts and are checked by `bun run check:nav`.
 *
 * Mirrors the React binding.
 */
const SOURCE_BASE = "https://github.com/Algorisys-Technologies/zen-ui/blob/main/";

const ViewCode = () => {
  const location = useLocation();
  /**
   * nav.ts stores base-less paths ("/carousel"), but Solid's useLocation gives
   * the pathname WITH the router base still on it ("/builder-solid/carousel"),
   * where React Router strips its basename. Stripping it here — if it is there —
   * is correct under either behaviour, and does not quietly become wrong if the
   * router changes its mind.
   */
  const routePath = () => {
    const base = import.meta.env.BASE_URL.replace(/\/$/, "");
    const p = location.pathname;
    return base && p.startsWith(base) ? p.slice(base.length) || "/" : p;
  };
  const href = () => {
    for (const group of NAV) {
      for (const item of group.items) {
        if (item.path === routePath() && item.source) return SOURCE_BASE + item.source;
      }
    }
    return undefined;
  };
  return (
    <Show when={href()}>
      {(h) => (
        <a
          class="app-home-link"
          href={h()}
          target="_blank"
          rel="noreferrer noopener"
          title="The demo source for this page on GitHub"
        >
          View code <span aria-hidden="true">↗</span>
        </a>
      )}
    </Show>
  );
};
import "./App.css";

/**
 * App shell — sticky header + collapsible sidebar + content area.
 * Mirrors the React demo's structure and CSS classes (see App.css,
 * copied verbatim from packages/react/src/App.css) so the two demos
 * read identically.
 *
 * Routes render inside an ErrorBoundary so a render-time crash in one
 * demo surfaces inline instead of silently leaving the content area
 * blank.
 */



const MenuIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
    <line x1="3" y1="12" x2="21" y2="12" />
    <line x1="3" y1="6" x2="21" y2="6" />
    <line x1="3" y1="18" x2="21" y2="18" />
  </svg>
);

const RouteError = (props: { err: unknown; reset: () => void }) => (
  <div style={{ padding: "1.5rem", "max-width": "50rem", margin: "0 auto" }}>
    <div
      style={{
        background: "var(--zen-color-error-soft)",
        color: "var(--zen-color-error-soft-fg)",
        border: "1px solid var(--zen-color-error)",
        "border-radius": "0.375rem",
        padding: "1rem",
      }}
    >
      <h2 style={{ margin: "0 0 0.5rem", "font-size": "1rem" }}>
        Demo failed to render
      </h2>
      <p style={{ margin: "0 0 0.625rem", "font-size": "0.8125rem" }}>
        {props.err instanceof Error ? props.err.message : String(props.err)}
      </p>
      <button
        onClick={() => props.reset()}
        style={{
          padding: "0.375rem 0.75rem",
          "border-radius": "0.25rem",
          border: "1px solid var(--zen-color-error)",
          background: "transparent",
          color: "inherit",
          cursor: "pointer",
          "font-size": "0.8125rem",
        }}
      >
        Retry
      </button>
      <details style={{ "margin-top": "0.625rem", "font-size": "0.75rem" }}>
        <summary style={{ cursor: "pointer" }}>Stack</summary>
        <pre style={{ overflow: "auto", "font-size": "0.6875rem", "white-space": "pre-wrap" }}>
          {props.err instanceof Error ? props.err.stack : ""}
        </pre>
      </details>
    </div>
  </div>
);

const App: Component<ParentProps> = (props) => {
  const { theme, setTheme, themes } = useTheme();
  const [collapsed, setCollapsed] = createSignal(false);
  const [query, setQuery] = createSignal("");

  /**
   * The sidebar filtered by the search box — the demo's own Search component,
   * dogfooded. Matches the label AND the nav description, so "wizard" finds
   * Stepper; a group with no hits disappears rather than sitting as an empty
   * heading. Empty query returns NAV itself, not a copy, so the unfiltered
   * sidebar renders exactly what it always did.
   */
  const filteredNav = () => {
    const q = query().trim().toLowerCase();
    if (!q) return NAV;
    return NAV.map((group) => ({
      ...group,
      items: group.items.filter(
        (item) =>
          item.label.toLowerCase().includes(q) ||
          (item.description?.toLowerCase().includes(q) ?? false),
      ),
    })).filter((group) => group.items.length > 0);
  };

  return (
    <div class="app-shell">
      <header class="app-header">
        <div class="app-header-left">
          <button
            type="button"
            class="sidebar-toggle"
            onClick={() => setCollapsed((v) => !v)}
            aria-label={collapsed() ? "Open sidebar" : "Close sidebar"}
          >
            <MenuIcon />
          </button>
          <div class="app-header-text">
            <h1 class="app-title">Zen UI · Solid</h1>
            <p class="app-subtitle">@algorisys/zen-ui-solid · component demo · {COMPONENT_COUNT} components</p>
          </div>
        </div>
        <div class="app-header-actions">
          {/* A real anchor, not the router's <A>: this leaves the SPA for the
              root site, so the router must not intercept it. */}
          <a class="app-home-link" href={ROOT_URL}>
            <span aria-hidden="true">←</span> All demos
          </a>
          <ViewCode />
          <label style={{
            display: "inline-flex",
            "align-items": "center",
            gap: "0.5rem",
            "font-size": "0.8125rem",
            color: "var(--zen-color-muted-fg)",
          }}>
            Theme
            <select
              value={theme()}
              onChange={(e) => setTheme(e.currentTarget.value as never)}
              style={{
                padding: "0.3125rem 0.5rem",
                "border-radius": "0.25rem",
                border: "1px solid var(--zen-color-border)",
                background: "var(--zen-color-background)",
                color: "var(--zen-color-foreground)",
                "font-size": "0.8125rem",
                cursor: "pointer",
              }}
            >
              <For each={themes}>{(t) => <option value={t.name}>{t.label}</option>}</For>
            </select>
          </label>
        </div>
      </header>

      <div class="app-body">
        <aside class={`sidebar ${collapsed() ? "is-collapsed" : ""}`}>
          <div class="sidebar-search">
            <Search
              size="sm"
              value={query()}
              onValueChange={setQuery}
              placeholder="Search components"
              aria-label="Search components"
            />
          </div>
          <nav>
            <Show
              when={filteredNav().length > 0}
              fallback={<p class="sidebar-empty">No components match “{query()}”.</p>}
            >
              <For each={filteredNav()}>
              {(group) => (
                <div class="sidebar-group">
                  <h3 class="sidebar-group-title">{group.group}</h3>
                  <ul class="sidebar-list">
                    <For each={group.items}>
                      {(item) => (
                        <li>
                          {/*
                            `sidebar-link` must appear ONLY in `class`. Router
                            puts activeClass/inactiveClass into a classList, and
                            listing `sidebar-link` there too meant that when a
                            link went active -> inactive the whole activeClass
                            token set was removed — stripping `sidebar-link`
                            itself. Links you had navigated away from rendered
                            unstyled.
                          */}
                          <A
                            href={item.path}
                            class="sidebar-link"
                            activeClass="sidebar-link-active"
                            inactiveClass="sidebar-link-inactive"
                            end
                          >
                            {item.label}
                          </A>
                        </li>
                      )}
                    </For>
                  </ul>
                </div>
              )}
              </For>
            </Show>
          </nav>
        </aside>
        <main class="app-content">
          <ErrorBoundary fallback={(err, reset) => <RouteError err={err} reset={reset} />}>
            {props.children}
          </ErrorBoundary>
        </main>
      </div>
      <footer class="app-footer">
        <span>
          © {new Date().getFullYear()}{" "}
          <a href="https://www.algorisys.com" target="_blank" rel="noreferrer noopener">
            Algorisys Technologies Pvt. Ltd
          </a>
          <span class="app-footer-sep">·</span>
          zen-ui · Kobalte-backed components
          {/* The licence, where someone evaluating the library is already
              looking. "Noncommercial" is the fact they need; the link carries
              the rest. Stated as what they MAY do, because a footer that only
              names a licence makes a reader go and find out what it means. */}
          <span class="app-footer-sep">·</span>
          <a
            href="https://github.com/Algorisys-Technologies/zen-ui/blob/main/LICENSE"
            target="_blank"
            rel="noreferrer noopener"
          >
            Free for noncommercial use
          </a>
        </span>
        <ReleaseNotes />
      </footer>
    </div>
  );
};

export default App;

// packages/react/src/App.tsx
import { useState } from "react";
import "./App.css";
import { NavLink, Routes, Route, useLocation } from "react-router-dom";
import { NAV } from "./nav";

/**
 * Derived from NAV, never hand-counted: nav.ts is already the single source of
 * truth for the sidebar and the landing catalogue, and a hard-coded number here
 * would drift the moment a component is added.
 *
 * Two exclusions, for two different reasons. `catalogue: false` groups (Getting
 * started) are routes rather than components. `components: false` groups
 * (Patterns) ARE on the landing page but are screens assembled from the
 * components above — counting them would count the same components twice.
 */
const COMPONENT_COUNT = NAV.filter((g) => g.catalogue !== false && g.components !== false).reduce(
  (n, g) => n + g.items.length,
  0,
);

/**
 * The root site, one level up from this demo's own base — derived, not "/".
 * The demo is mounted at /builder/ under `dev:all` and at /zen-ui/builder/ on
 * GH-Pages, and the way out has to land on the right root in both. Hardcoding
 * "/" would walk out of the deployment entirely.
 */
const ROOT_URL = new URL("..", new URL(import.meta.env.BASE_URL, window.location.origin))
  .pathname;

/**
 * "View code" opens the demo file for the route you are on — the USAGE, not the
 * component's internals. The page already prints a snippet, but that snippet is
 * a hand-typed `code` string sitting next to the JSX it claims to describe, and
 * nothing keeps the two honest. This is the file that actually ran.
 *
 * Pinned to `main` rather than the current branch: a link that only resolves on
 * whatever branch happened to build it is a link that breaks on every other one.
 * The paths come from nav.ts and are checked by `bun run check:nav`.
 */
const SOURCE_BASE = "https://github.com/Algorisys-Technologies/zen-ui/blob/main/";

/** The nav entry for the current route, if it has a source. */
const useSourceHref = (): string | undefined => {
  const { pathname } = useLocation();
  for (const group of NAV) {
    for (const item of group.items) {
      if (item.to === pathname && item.source) return SOURCE_BASE + item.source;
    }
  }
  return undefined;
};

const ViewCode: React.FC = () => {
  const href = useSourceHref();
  if (!href) return null;
  return (
    <a
      className="app-home-link"
      href={href}
      target="_blank"
      rel="noreferrer noopener"
      title="The demo source for this page on GitHub"
    >
      View code <span aria-hidden>↗</span>
    </a>
  );
};

import Welcome from "./components/Welcome";
import ThemeSwitcher from "./components/theme-switcher";

import NewButtonDemo from "./components/NewButtonDemo";
import NewTooltipDemo from "./components/NewTooltipDemo";
import NewDropdownMenuDemo from "./components/NewDropdownMenuDemo";
import NewSeparatorDemo from "./components/NewSeparatorDemo";
import NewSwitchDemo from "./components/NewSwitchDemo";
import NewCheckboxDemo from "./components/NewCheckboxDemo";
import NewRadioGroupDemo from "./components/NewRadioGroupDemo";
import NewProgressDemo from "./components/NewProgressDemo";
import NewAvatarDemo from "./components/NewAvatarDemo";
import NewBadgeDemo from "./components/NewBadgeDemo";
import NewSkeletonDemo from "./components/NewSkeletonDemo";
import NewLoadingDemo from "./components/NewLoadingDemo";
import NewSelectDemo from "./components/NewSelectDemo";
import NewSliderDemo from "./components/NewSliderDemo";
import NewScrollAreaDemo from "./components/NewScrollAreaDemo";
import NewInputDemo from "./components/NewInputDemo";
import SearchDemo from "./components/SearchDemo";
import PasswordInputDemo from "./components/PasswordInputDemo";
import NewNumberFieldDemo from "./components/NewNumberFieldDemo";
import NewDatePickerDemo from "./components/NewDatePickerDemo";
import NewOTPDemo from "./components/NewOTPDemo";
import NewPhoneInputDemo from "./components/NewPhoneInputDemo";
import NewFABDemo from "./components/NewFABDemo";
import NewFormDemo from "./components/NewFormDemo";
import NewDataTableDemo from "./components/NewDataTableDemo";
import NewTreeTableDemo from "./components/NewTreeTableDemo";
import NewMicroChartDemo from "./components/NewMicroChartDemo";
import NewCountdownDemo from "./components/NewCountdownDemo";
import NewCodeEditorDemo from "./components/NewCodeEditorDemo";
import NewSpreadsheetGridDemo from "./components/NewSpreadsheetGridDemo";
import NewProctorDemo from "./components/NewProctorDemo";
import NewChunkUploaderDemo from "./components/NewChunkUploaderDemo";
import NewDiagramCanvasDemo from "./components/NewDiagramCanvasDemo";
import NewDiffViewDemo from "./components/NewDiffViewDemo";
import NewDocumentViewerDemo from "./components/NewDocumentViewerDemo";
import NewSplitterDemo from "./components/NewSplitterDemo";
import NewSortableListDemo from "./components/NewSortableListDemo";
import NewTimelineDemo from "./components/NewTimelineDemo";
import NewUploadCollectionDemo from "./components/NewUploadCollectionDemo";
import NewPlanningCalendarDemo from "./components/NewPlanningCalendarDemo";
import NewGanttDemo from "./components/NewGanttDemo";
import NewProductionScheduleDemo from "./components/NewProductionScheduleDemo";
import NewLazyOptionsDemo from "./components/NewLazyOptionsDemo";
import NewComboboxDemo from "./components/NewComboboxDemo";
import NewAlertDemo from "./components/NewAlertDemo";
import NewDialogDemo from "./components/NewDialogDemo";
import NewToastDemo from "./components/NewToastDemo";
import NewFileUploadDemo from "./components/NewFileUploadDemo";
import NewBoundFieldsDemo from "./components/NewBoundFieldsDemo";
import NewStepperDemo from "./components/NewStepperDemo";
import NewBannerDemo from "./components/NewBannerDemo";
import NewEmptyStateDemo from "./components/NewEmptyStateDemo";
import NewTabsDemo from "./components/NewTabsDemo";
import NewAccordionDemo from "./components/NewAccordionDemo";
import NewCollapsibleDemo from "./components/NewCollapsibleDemo";
import NewLabelDemo from "./components/NewLabelDemo";
import NewCardDemo from "./components/NewCardDemo";
import NewSheetDemo from "./components/NewSheetDemo";
import NewDateRangePickerDemo from "./components/NewDateRangePickerDemo";
import NewTagInputDemo from "./components/NewTagInputDemo";
import NewMultiComboboxDemo from "./components/NewMultiComboboxDemo";
import NewRatingDemo from "./components/NewRatingDemo";
import NewNpsDemo from "./components/NewNpsDemo";
import NewLikertDemo from "./components/NewLikertDemo";
import NewTimePickerDemo from "./components/NewTimePickerDemo";
import NewDateTimePickerDemo from "./components/NewDateTimePickerDemo";
import NewQRScannerDemo from "./components/NewQRScannerDemo";
import NewNotificationsInboxDemo from "./components/NewNotificationsInboxDemo";
import NewBreadcrumbDemo from "./components/NewBreadcrumbDemo";
import NewPaginationDemo from "./components/NewPaginationDemo";
import NewSidebarDemo from "./components/NewSidebarDemo";
import NewChartDemo from "./components/NewChartDemo";
import NewRichTextDemo from "./components/NewRichTextDemo";
import NewMapDemo from "./components/NewMapDemo";
import NewCameraDemo from "./components/NewCameraDemo";
import NewIconDemo from "./components/NewIconDemo";
import NewObjectDemo from "./components/NewObjectDemo";
import NewButtonFamilyDemo from "./components/NewButtonFamilyDemo";
import NewTreeDemo from "./components/NewTreeDemo";
import NewToolbarDemo from "./components/NewToolbarDemo";
import NewShellBarDemo from "./components/NewShellBarDemo";
import SkipToContentDemo from "./components/SkipToContentDemo";
import NewFlexibleColumnLayoutDemo from "./components/NewFlexibleColumnLayoutDemo";
import NewDynamicPageDemo from "./components/NewDynamicPageDemo";
import NewObjectPageDemo from "./components/NewObjectPageDemo";
import NewSelectDialogDemo from "./components/NewSelectDialogDemo";
import NewValueHelpDemo from "./components/NewValueHelpDemo";
import NewViewSettingsDemo from "./components/NewViewSettingsDemo";
import NewFilterBarDemo from "./components/NewFilterBarDemo";
import NewPageHeaderDemo from "./components/NewPageHeaderDemo";
import NewStatCardDemo from "./components/NewStatCardDemo";
import NewCustomizingDemo from "./components/NewCustomizingDemo";
import NewMaskInputDemo from "./components/NewMaskInputDemo";
import NewPopoverDemo from "./components/NewPopoverDemo";
import NewLinkDemo from "./components/NewLinkDemo";
import NewThemeDemo from "./components/NewThemeDemo";
import NewDirectionDemo from "./components/NewDirectionDemo";
import NewPageDemo from "./components/NewPageDemo";
import NewMessagePopoverDemo from "./components/NewMessagePopoverDemo";
import NewColorPickerDemo from "./components/NewColorPickerDemo";
import NewCarouselDemo from "./components/NewCarouselDemo";
import NewDynamicDateRangeDemo from "./components/NewDynamicDateRangeDemo";
import NewListReportDemo from "./components/NewListReportDemo";
import NewPivotDemo from "./components/NewPivotDemo";
import NewMediaTimelineDemo from "./components/NewMediaTimelineDemo";
import NewWaveformDemo from "./components/NewWaveformDemo";
import ReleaseNotes from "./components/ReleaseNotes";
import { Toaster } from "./components/toast/toaster";
import { Search } from "./components/form/search/search";

/**
 * Navigation data — single source of truth for the sidebar.
 * Add a new component's route here and it shows up under the right group.
 */


const Sidebar: React.FC<{ collapsed: boolean }> = ({ collapsed }) => {
  const [query, setQuery] = useState("");
  /**
   * The sidebar filtered by the search box — the library's own Search
   * component, dogfooded. Matches the label AND the nav description, so
   * "wizard" finds Stepper; a group with no hits disappears rather than
   * sitting as an empty heading. Empty query returns NAV itself, so the
   * unfiltered sidebar renders exactly what it always did.
   */
  const q = query.trim().toLowerCase();
  const filteredNav = !q
    ? NAV
    : NAV.map((group) => ({
        ...group,
        items: group.items.filter(
          (item) =>
            item.label.toLowerCase().includes(q) ||
            (item.description?.toLowerCase().includes(q) ?? false),
        ),
      })).filter((group) => group.items.length > 0);
  return (
    <aside className={`sidebar${collapsed ? " is-collapsed" : ""}`} aria-hidden={collapsed}>
      <div className="sidebar-search">
        <Search
          size="sm"
          value={query}
          onValueChange={setQuery}
          placeholder="Search components"
          aria-label="Search components"
        />
      </div>
      {filteredNav.length === 0 ? (
        <p className="sidebar-empty">No components match “{query}”.</p>
      ) : (
        filteredNav.map((group) => (
          <div key={group.title} className="sidebar-group">
            <h4 className="sidebar-group-title">{group.title}</h4>
            <ul className="sidebar-list">
              {group.items.map((item) => (
                <li key={item.to}>
                  <NavLink
                    to={item.to}
                    end={item.to === "/"}
                    className={({ isActive }) =>
                      isActive
                        ? "sidebar-link sidebar-link-active"
                        : "sidebar-link sidebar-link-inactive"
                    }
                  >
                    {item.label}
                  </NavLink>
                </li>
              ))}
            </ul>
          </div>
        ))
      )}
    </aside>
  );
};

const SidebarToggle: React.FC<{
  collapsed: boolean;
  onToggle: () => void;
}> = ({ collapsed, onToggle }) => (
  <button
    type="button"
    className="sidebar-toggle"
    onClick={onToggle}
    aria-label={collapsed ? "Open sidebar" : "Close sidebar"}
    aria-expanded={!collapsed}
  >
    <svg
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <line x1="3" y1="6" x2="21" y2="6" />
      <line x1="3" y1="12" x2="21" y2="12" />
      <line x1="3" y1="18" x2="21" y2="18" />
    </svg>
  </button>
);

const SIDEBAR_KEY = "zen-sidebar-collapsed";

const App: React.FC = () => {
  const [collapsed, setCollapsed] = useState<boolean>(() => {
    if (typeof window === "undefined") return false;
    try {
      return window.localStorage.getItem(SIDEBAR_KEY) === "1";
    } catch {
      return false;
    }
  });
  const toggleSidebar = () => {
    setCollapsed((prev) => {
      const next = !prev;
      try {
        window.localStorage.setItem(SIDEBAR_KEY, next ? "1" : "0");
      } catch {
        /* ignore quota */
      }
      return next;
    });
  };

  return (
    <div className="app-shell">
      <header className="app-header">
        <div className="app-header-left">
          <SidebarToggle collapsed={collapsed} onToggle={toggleSidebar} />
          <div className="app-header-text">
            <h1 className="app-title">Zen UI Component Library</h1>
            <p className="app-subtitle">
              shadcn / Radix-style React component library by Algorisys ·{" "}
              {COMPONENT_COUNT} components
            </p>
          </div>
        </div>
        <div className="app-header-actions">
          {/* A real anchor: this leaves the SPA for the root site, so the
              router must not intercept it. */}
          <a className="app-home-link" href={ROOT_URL}>
            <span aria-hidden>←</span> All demos
          </a>
          <ViewCode />
          <ThemeSwitcher />
        </div>
      </header>
      <div className="app-body">
        <Sidebar collapsed={collapsed} />
        <main className="app-content">
          <Routes>
            <Route path="/" element={<Welcome />} />

            <Route path="/button-new" element={<NewButtonDemo />} />
            <Route path="/tooltip-new" element={<NewTooltipDemo />} />
            <Route path="/dropdown-menu" element={<NewDropdownMenuDemo />} />
            <Route path="/separator" element={<NewSeparatorDemo />} />
            <Route path="/switch-new" element={<NewSwitchDemo />} />
            <Route path="/checkbox-new" element={<NewCheckboxDemo />} />
            <Route path="/radio-group" element={<NewRadioGroupDemo />} />
            <Route path="/progress-new" element={<NewProgressDemo />} />
            <Route path="/avatar-new" element={<NewAvatarDemo />} />
            <Route path="/badge-new" element={<NewBadgeDemo />} />
            <Route path="/skeleton-new" element={<NewSkeletonDemo />} />
            <Route path="/loading-new" element={<NewLoadingDemo />} />
            <Route path="/select-new" element={<NewSelectDemo />} />
            <Route path="/slider-new" element={<NewSliderDemo />} />
            <Route path="/scroll-area-new" element={<NewScrollAreaDemo />} />
            <Route path="/input-new" element={<NewInputDemo />} />
            <Route path="/search" element={<SearchDemo />} />
            <Route path="/password-input" element={<PasswordInputDemo />} />
            <Route path="/number-field-new" element={<NewNumberFieldDemo />} />
            <Route path="/date-picker-new" element={<NewDatePickerDemo />} />
            <Route path="/otp-new" element={<NewOTPDemo />} />
            <Route path="/phone-input-new" element={<NewPhoneInputDemo />} />
            <Route path="/fab-new" element={<NewFABDemo />} />
            <Route path="/form-new" element={<NewFormDemo />} />
            <Route path="/data-table" element={<NewDataTableDemo />} />
            <Route path="/tree-table" element={<NewTreeTableDemo />} />
            <Route path="/micro-chart" element={<NewMicroChartDemo />} />
            <Route path="/countdown" element={<NewCountdownDemo />} />
            <Route path="/code-editor" element={<NewCodeEditorDemo />} />
            <Route path="/spreadsheet-grid" element={<NewSpreadsheetGridDemo />} />
            <Route path="/proctor" element={<NewProctorDemo />} />
            <Route path="/chunk-uploader" element={<NewChunkUploaderDemo />} />
            <Route path="/diagram-canvas" element={<NewDiagramCanvasDemo />} />
            <Route path="/diff-view" element={<NewDiffViewDemo />} />
            <Route path="/document-viewer" element={<NewDocumentViewerDemo />} />
            <Route path="/splitter" element={<NewSplitterDemo />} />
            <Route path="/sortable-list" element={<NewSortableListDemo />} />
            <Route path="/timeline" element={<NewTimelineDemo />} />
            <Route path="/upload-collection" element={<NewUploadCollectionDemo />} />
            <Route path="/planning-calendar" element={<NewPlanningCalendarDemo />} />
            <Route path="/gantt" element={<NewGanttDemo />} />
            <Route path="/production-schedule" element={<NewProductionScheduleDemo />} />
            <Route path="/lazy-options" element={<NewLazyOptionsDemo />} />
            <Route path="/combobox" element={<NewComboboxDemo />} />
            <Route path="/alert" element={<NewAlertDemo />} />
            <Route path="/dialog" element={<NewDialogDemo />} />
            <Route path="/toast" element={<NewToastDemo />} />
            <Route path="/file-upload" element={<NewFileUploadDemo />} />
            <Route path="/form-bound" element={<NewBoundFieldsDemo />} />
            <Route path="/stepper" element={<NewStepperDemo />} />
            <Route path="/banner" element={<NewBannerDemo />} />
            <Route path="/empty-state" element={<NewEmptyStateDemo />} />
            <Route path="/tabs" element={<NewTabsDemo />} />
            <Route path="/accordion" element={<NewAccordionDemo />} />
            <Route path="/collapsible" element={<NewCollapsibleDemo />} />
            <Route path="/label" element={<NewLabelDemo />} />
            <Route path="/card" element={<NewCardDemo />} />
            <Route path="/sheet" element={<NewSheetDemo />} />
            <Route path="/date-range-picker" element={<NewDateRangePickerDemo />} />
            <Route path="/tag-input" element={<NewTagInputDemo />} />
            <Route path="/multi-combobox" element={<NewMultiComboboxDemo />} />
            <Route path="/rating" element={<NewRatingDemo />} />
            <Route path="/nps" element={<NewNpsDemo />} />
            <Route path="/likert" element={<NewLikertDemo />} />
            <Route path="/time-picker" element={<NewTimePickerDemo />} />
            <Route path="/date-time-picker" element={<NewDateTimePickerDemo />} />
            <Route path="/qr-scanner" element={<NewQRScannerDemo />} />
            <Route path="/notifications-inbox" element={<NewNotificationsInboxDemo />} />
            <Route path="/breadcrumb" element={<NewBreadcrumbDemo />} />
            <Route path="/pagination" element={<NewPaginationDemo />} />
            <Route path="/sidebar" element={<NewSidebarDemo />} />
            <Route path="/chart" element={<NewChartDemo />} />
            <Route path="/rich-text" element={<NewRichTextDemo />} />
            <Route path="/map" element={<NewMapDemo />} />
            <Route path="/camera" element={<NewCameraDemo />} />
            <Route path="/icon" element={<NewIconDemo />} />
            <Route path="/object" element={<NewObjectDemo />} />
            <Route path="/button-family" element={<NewButtonFamilyDemo />} />
            <Route path="/tree" element={<NewTreeDemo />} />
            <Route path="/toolbar" element={<NewToolbarDemo />} />
            <Route path="/skip-to-content" element={<SkipToContentDemo />} />
            <Route path="/shellbar" element={<NewShellBarDemo />} />
            <Route
              path="/flexible-column-layout"
              element={<NewFlexibleColumnLayoutDemo />}
            />
            <Route path="/dynamic-page" element={<NewDynamicPageDemo />} />
            <Route path="/object-page" element={<NewObjectPageDemo />} />
            <Route path="/select-dialog" element={<NewSelectDialogDemo />} />
            <Route path="/value-help" element={<NewValueHelpDemo />} />
            <Route path="/view-settings" element={<NewViewSettingsDemo />} />
            <Route path="/filter-bar" element={<NewFilterBarDemo />} />
            <Route path="/page-header" element={<NewPageHeaderDemo />} />
            <Route path="/stat-card" element={<NewStatCardDemo />} />
            <Route path="/customizing" element={<NewCustomizingDemo />} />
            <Route path="/mask-input" element={<NewMaskInputDemo />} />
            <Route path="/popover" element={<NewPopoverDemo />} />
            <Route path="/link" element={<NewLinkDemo />} />
            <Route path="/theme" element={<NewThemeDemo />} />
            <Route path="/direction" element={<NewDirectionDemo />} />
            <Route path="/page" element={<NewPageDemo />} />
            <Route path="/message-popover" element={<NewMessagePopoverDemo />} />
            <Route path="/color-picker" element={<NewColorPickerDemo />} />
            <Route path="/carousel" element={<NewCarouselDemo />} />
            <Route path="/dynamic-date-range" element={<NewDynamicDateRangeDemo />} />
            <Route path="/list-report" element={<NewListReportDemo />} />
            <Route path="/pivot" element={<NewPivotDemo />} />
            <Route path="/media-timeline" element={<NewMediaTimelineDemo />} />
            <Route path="/waveform" element={<NewWaveformDemo />} />
          </Routes>
        </main>
      </div>
      <footer className="app-footer">
        <span>
          © {new Date().getFullYear()}{" "}
          <a href="https://www.algorisys.com" target="_blank" rel="noreferrer noopener">
            Algorisys Technologies Pvt. Ltd
          </a>
          <span className="app-footer-sep">·</span>
          zen-ui · shadcn / Radix-style components
          {/* The licence, where someone evaluating the library is already
              looking. "Noncommercial" is the fact they need; the link carries
              the rest. Stated as what they MAY do, because a footer that only
              names a licence makes a reader go and find out what it means. */}
          <span className="app-footer-sep">·</span>
          <a
            href="https://github.com/Algorisys-Technologies/zen-ui/blob/main/LICENSE"
            target="_blank"
            rel="noreferrer noopener"
          >
            Free for noncommercial use
          </a>
        </span>
        <ReleaseNotes />
      </footer>
      {/* Mounted once near the root so toast({...}) can be called from
       * anywhere in the demo tree. */}
      <Toaster />
    </div>
  );
};

export default App;
