// packages/react/src/components/tree-table/tree-table.tsx
import * as React from "react";
import {
  flexRender,
  getCoreRowModel,
  getExpandedRowModel,
  getFilteredRowModel,
  getSortedRowModel,
  useReactTable,
  type ColumnDef,
  type ExpandedState,
  type Row,
  type RowSelectionState,
  type SortingState,
} from "@tanstack/react-table";
import { arrowStep } from "@algorisys/zen-ui-core";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../data-table/table";
import { Checkbox } from "../form/checkbox/checkbox";
import { Icon } from "../icon/icon";
import { Input } from "../form/input/input";
import { Button } from "../button/button";
import { cn } from "../../lib/cn";

/**
 * TreeTable — a table whose rows form a hierarchy.
 *
 *   <TreeTable data={accounts} columns={columns} />
 *
 * This is a separate component from `DataTable` rather than a mode of it, and
 * the reason is structural rather than a matter of size. Hierarchy and grouping
 * claim the SAME three slots in a TanStack table: `subRows`, the `expanded`
 * state, and the chevron column. DataTable's grouping synthesizes its group
 * rows *as* subRows, so a table cannot carry both a real hierarchy and a
 * grouped one — the second would nest inside the first and mean nothing.
 *
 * What that buys, beyond avoiding a mutual-exclusion gate: the chevron lives
 * INSIDE the first column here, indented by depth, rather than in a leading
 * gutter column the way DataTable's `renderSubRow` toggle does. That is what
 * makes the hierarchy readable — you follow one column down the page.
 *
 * Reach for `DataTable` for flat data with grouping, virtualization, pagination
 * and inline editing; reach for this when the data is genuinely nested and the
 * nesting is the point.
 */

/** The default child accessor: a `children` array, which is what nested JSON usually calls it. */
const defaultGetSubRows = <TData,>(row: TData): TData[] | undefined =>
  (row as { children?: TData[] }).children;

export interface TreeTableProps<TData, TValue = unknown> {
  data: TData[];
  columns: ColumnDef<TData, TValue>[];
  /**
   * Where a row's children live. Defaults to `row.children`.
   * Return `undefined` (not `[]`) for a leaf — an empty array still reads as
   * "expandable, but empty" and renders a chevron that does nothing.
   */
  getSubRows?: (row: TData) => TData[] | undefined;
  getRowId?: (originalRow: TData, index: number, parent?: Row<TData>) => string;

  /* expansion */
  expanded?: ExpandedState;
  /** `true` expands everything on first render. */
  defaultExpanded?: ExpandedState;
  onExpandedChange?: (state: ExpandedState) => void;
  /** Show the expand-all / collapse-all control. Default true. */
  enableExpandAll?: boolean;

  /* sorting — sorts within each parent's children, never across levels */
  enableSorting?: boolean;
  sorting?: SortingState;
  onSortingChange?: (state: SortingState) => void;

  /* filtering */
  enableGlobalFilter?: boolean;
  globalFilter?: string;
  onGlobalFilterChange?: (value: string) => void;
  globalFilterPlaceholder?: string;

  /* selection */
  enableRowSelection?: boolean;
  /** Selecting a parent selects its descendants. Default true. */
  enableSubRowSelection?: boolean;
  rowSelection?: RowSelectionState;
  onRowSelectionChange?: (state: RowSelectionState) => void;

  /* presentation */
  /** Which column carries the chevron. Defaults to the first visible column. */
  hierarchyColumnId?: string;
  /** Pixels of indent per level. Default 20. */
  indent?: number;
  stickyHeader?: boolean;
  headerVariant?: "plain" | "underline" | "branded";
  maxBodyHeight?: number;
  rowClassName?: (row: Row<TData>) => string | undefined;
  onRowClick?: (row: Row<TData>) => void;
  emptyMessage?: string;
  loading?: boolean;
  className?: string;
}

export function TreeTable<TData, TValue = unknown>({
  data,
  columns,
  getSubRows,
  getRowId,
  expanded,
  defaultExpanded,
  onExpandedChange,
  enableExpandAll = true,
  enableSorting = true,
  sorting,
  onSortingChange,
  enableGlobalFilter,
  globalFilter,
  onGlobalFilterChange,
  globalFilterPlaceholder,
  enableRowSelection,
  enableSubRowSelection = true,
  rowSelection,
  onRowSelectionChange,
  hierarchyColumnId,
  indent = 20,
  stickyHeader,
  headerVariant = "plain",
  maxBodyHeight,
  rowClassName,
  onRowClick,
  emptyMessage = "No results.",
  loading,
  className,
}: TreeTableProps<TData, TValue>) {
  const [expandedInner, setExpandedInner] = React.useState<ExpandedState>(defaultExpanded ?? {});
  const [sortingInner, setSortingInner] = React.useState<SortingState>([]);
  const [selectionInner, setSelectionInner] = React.useState<RowSelectionState>({});
  const [globalFilterInner, setGlobalFilterInner] = React.useState("");

  const expandedState = expanded ?? expandedInner;
  const sortingState = sorting ?? sortingInner;
  const selectionState = rowSelection ?? selectionInner;
  const globalFilterState = globalFilter ?? globalFilterInner;

  /* The selection checkbox goes in its own leading column; the chevron does
   * NOT, because it belongs to the hierarchy column's text. */
  const augmentedColumns = React.useMemo<ColumnDef<TData, TValue>[]>(() => {
    if (!enableRowSelection) return columns;
    const select: ColumnDef<TData, TValue> = {
      id: "__select__",
      header: ({ table }) => (
        <Checkbox
          checked={
            table.getIsAllRowsSelected()
              ? true
              : table.getIsSomeRowsSelected()
                ? "indeterminate"
                : false
          }
          onCheckedChange={(v) => table.toggleAllRowsSelected(v === true)}
          aria-label="Select all rows"
        />
      ),
      cell: ({ row }) => {
        /*
         * A parent's checkbox describes its SUBTREE, not its own row entry.
         * `getIsSelected()` alone is that entry, and TanStack never clears it
         * when a descendant is unticked — so a parent whose child you just
         * unticked would keep rendering "checked" while the row below it says
         * otherwise. Measured in the Solid binding: tick Engineering, untick
         * Infrastructure, and the naive version leaves Engineering checked.
         */
        const hasChildren = row.subRows.length > 0;
        const checked = hasChildren
          ? row.getIsSelected() && row.getIsAllSubRowsSelected()
          : row.getIsSelected();
        const partial = !checked && (row.getIsSomeSelected() || (hasChildren && row.getIsSelected()));
        return (
          <Checkbox
            // Radix is natively tri-state, so unlike Solid's separate
            // `indeterminate` prop the three states collapse into one value.
            checked={checked ? true : partial ? "indeterminate" : false}
            onCheckedChange={(v) => row.toggleSelected(v === true)}
            aria-label={`Select row ${row.index + 1}`}
          />
        );
      },
      enableSorting: false,
      enableHiding: false,
      size: 36,
    };
    return [select, ...columns];
  }, [columns, enableRowSelection]);

  const table = useReactTable<TData>({
    data,
    columns: augmentedColumns as ColumnDef<TData, unknown>[],
    state: {
      expanded: expandedState,
      sorting: sortingState,
      rowSelection: selectionState,
      globalFilter: globalFilterState,
    },
    getSubRows: getSubRows ?? defaultGetSubRows,
    getRowId,
    enableSorting,
    enableRowSelection: !!enableRowSelection,
    enableSubRowSelection,
    /*
     * Filter from the leaves up, so a matching child keeps its ancestors on
     * screen. The default drops any row that does not match ITSELF, which for a
     * tree means a hit three levels down takes its whole path with it and the
     * user sees an empty table while the count says otherwise.
     */
    filterFromLeafRows: true,
    onExpandedChange: (updater) => {
      const next = typeof updater === "function" ? updater(expandedState) : updater;
      if (expanded === undefined) setExpandedInner(next);
      onExpandedChange?.(next);
    },
    onSortingChange: (updater) => {
      const next = typeof updater === "function" ? updater(sortingState) : updater;
      if (sorting === undefined) setSortingInner(next);
      onSortingChange?.(next);
    },
    onRowSelectionChange: (updater) => {
      const next = typeof updater === "function" ? updater(selectionState) : updater;
      if (rowSelection === undefined) setSelectionInner(next);
      onRowSelectionChange?.(next);
    },
    onGlobalFilterChange: (updater) => {
      const next = typeof updater === "function" ? updater(globalFilterState) : updater;
      if (globalFilter === undefined) setGlobalFilterInner(next);
      onGlobalFilterChange?.(next);
    },
    getCoreRowModel: getCoreRowModel(),
    getExpandedRowModel: getExpandedRowModel(),
    getSortedRowModel: enableSorting ? getSortedRowModel() : undefined,
    getFilteredRowModel: enableGlobalFilter ? getFilteredRowModel() : undefined,
  });

  const rows = table.getRowModel().rows;

  /** The column the hierarchy reads down. */
  const hierarchyId =
    hierarchyColumnId ?? table.getVisibleLeafColumns().find((c) => !c.id.startsWith("__"))?.id;

  /*
   * aria-posinset / aria-setsize are per-parent, not per-page: a treegrid row's
   * "set" is its siblings. TanStack's flat row model does not carry that, so it
   * is counted once per render rather than walked per row.
   */
  const siblingInfo = React.useMemo(() => {
    const info = new Map<string, { pos: number; size: number }>();
    const byParent = new Map<string, Row<TData>[]>();
    for (const row of rows) {
      const key = row.parentId ?? "";
      const list = byParent.get(key);
      if (list) list.push(row);
      else byParent.set(key, [row]);
    }
    for (const list of byParent.values()) {
      list.forEach((row, i) => info.set(row.id, { pos: i + 1, size: list.length }));
    }
    return info;
  }, [rows]);

  /* ---- roving focus, the WAI-ARIA treegrid row pattern ---- */
  const rowRefs = React.useRef(new Map<string, HTMLTableRowElement>());
  const [focusedId, setFocusedId] = React.useState<string | null>(null);
  const activeId = focusedId ?? rows[0]?.id;

  const focusRow = (id: string | undefined | null) => {
    if (!id) return;
    setFocusedId(id);
    rowRefs.current.get(id)?.focus();
  };

  const moveBy = (from: Row<TData>, delta: number) => {
    const i = rows.findIndex((r) => r.id === from.id);
    focusRow(rows[i + delta]?.id);
  };

  const onRowKeyDown = (e: React.KeyboardEvent<HTMLTableRowElement>, row: Row<TData>) => {
    const step = arrowStep(e.key, e.currentTarget);
    if (e.key === "ArrowDown") {
      e.preventDefault();
      moveBy(row, 1);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      moveBy(row, -1);
    } else if (step === 1) {
      // Forward: open a closed node, else descend into it.
      e.preventDefault();
      if (row.getCanExpand() && !row.getIsExpanded()) row.toggleExpanded(true);
      else if (row.getIsExpanded()) moveBy(row, 1);
    } else if (step === -1) {
      // Backward: close an open node, else climb to the parent.
      e.preventDefault();
      if (row.getIsExpanded()) row.toggleExpanded(false);
      else if (row.parentId) focusRow(row.parentId);
    } else if (e.key === "Home") {
      e.preventDefault();
      focusRow(rows[0]?.id);
    } else if (e.key === "End") {
      e.preventDefault();
      focusRow(rows[rows.length - 1]?.id);
    } else if (e.key === "Enter" || e.key === " ") {
      if (onRowClick) {
        e.preventDefault();
        onRowClick(row);
      } else if (row.getCanExpand()) {
        e.preventDefault();
        row.toggleExpanded();
      }
    }
  };

  const headerVariantRowClass =
    headerVariant === "branded"
      ? "zen-bg-zen-primary-soft [&>th]:zen-text-zen-primary-soft-fg [&>th]:zen-font-semibold"
      : "";
  const headerVariantTheadClass =
    headerVariant === "underline"
      ? "[&_tr:last-child]:zen-border-b-2 [&_tr:last-child]:zen-border-zen-primary"
      : "";
  const stickyRowClass = stickyHeader
    ? headerVariant === "branded"
      ? "zen-sticky zen-top-0 zen-z-10"
      : "zen-sticky zen-top-0 zen-z-10 zen-bg-zen-background"
    : "";

  const showToolbar = enableGlobalFilter || enableExpandAll;

  return (
    <div className={cn("zen-flex zen-w-full zen-flex-col zen-gap-3", className)}>
      {showToolbar && (
        <div className="zen-flex zen-flex-wrap zen-items-center zen-gap-2">
          {enableGlobalFilter && (
            <Input
              value={globalFilterState}
              onChange={(e) => table.setGlobalFilter(e.target.value)}
              placeholder={globalFilterPlaceholder ?? "Search…"}
              className="zen-max-w-xs"
              aria-label="Search"
            />
          )}
          {enableExpandAll && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => table.toggleAllRowsExpanded()}
              aria-expanded={table.getIsAllRowsExpanded()}
            >
              <Icon
                name={table.getIsAllRowsExpanded() ? "chevron-down" : "chevron-right"}
                size={14}
              />
              {table.getIsAllRowsExpanded() ? "Collapse all" : "Expand all"}
            </Button>
          )}
        </div>
      )}

      <Table
        role="treegrid"
        aria-busy={loading || undefined}
        containerClassName={maxBodyHeight ? "zen-overflow-auto" : undefined}
        containerStyle={maxBodyHeight ? { maxHeight: `${maxBodyHeight}px` } : undefined}
      >
        <TableHeader className={headerVariantTheadClass}>
          {table.getHeaderGroups().map((group) => (
            <TableRow key={group.id} className={cn(headerVariantRowClass, stickyRowClass)}>
              {group.headers.map((header) => {
                const sorted = header.column.getIsSorted();
                return (
                  <TableHead
                    key={header.id}
                    style={header.column.getSize() ? { width: header.getSize() } : undefined}
                    aria-sort={
                      sorted === "asc"
                        ? "ascending"
                        : sorted === "desc"
                          ? "descending"
                          : header.column.getCanSort()
                            ? "none"
                            : undefined
                    }
                  >
                    {!header.isPlaceholder &&
                      (header.column.getCanSort() ? (
                        <button
                          type="button"
                          onClick={header.column.getToggleSortingHandler()}
                          className="zen-inline-flex zen-items-center zen-gap-1 zen-border-0 zen-bg-transparent zen-p-0 zen-font-inherit zen-text-inherit zen-cursor-pointer focus-visible:zen-outline-none focus-visible:zen-ring-2 focus-visible:zen-ring-zen-ring"
                        >
                          {flexRender(header.column.columnDef.header, header.getContext())}
                          {sorted && (
                            <Icon name={sorted === "asc" ? "chevron-up" : "chevron-down"} size={12} />
                          )}
                        </button>
                      ) : (
                        flexRender(header.column.columnDef.header, header.getContext())
                      ))}
                  </TableHead>
                );
              })}
            </TableRow>
          ))}
        </TableHeader>

        <TableBody>
          {loading || rows.length === 0 ? (
            <TableRow>
              <TableCell
                colSpan={table.getVisibleLeafColumns().length}
                className="zen-h-24 zen-text-center zen-text-zen-muted-fg"
              >
                {loading ? "Loading…" : emptyMessage}
              </TableCell>
            </TableRow>
          ) : (
            rows.map((row) => {
              const info = siblingInfo.get(row.id);
              return (
                <TableRow
                  key={row.id}
                  ref={(el) => {
                    if (el) rowRefs.current.set(row.id, el);
                    else rowRefs.current.delete(row.id);
                  }}
                  data-state={row.getIsSelected() ? "selected" : undefined}
                  data-depth={row.depth}
                  className={cn(
                    "focus-visible:zen-outline-none focus-visible:zen-ring-2 focus-visible:zen-ring-zen-ring focus-visible:zen-ring-inset",
                    onRowClick && "zen-cursor-pointer",
                    rowClassName?.(row),
                  )}
                  // aria-level is 1-based; TanStack's depth is 0-based.
                  aria-level={row.depth + 1}
                  aria-expanded={row.getCanExpand() ? row.getIsExpanded() : undefined}
                  aria-posinset={info?.pos}
                  aria-setsize={info?.size}
                  aria-selected={enableRowSelection ? row.getIsSelected() : undefined}
                  tabIndex={activeId === row.id ? 0 : -1}
                  onFocus={() => setFocusedId(row.id)}
                  onKeyDown={(e) => onRowKeyDown(e, row)}
                  onClick={() => onRowClick?.(row)}
                >
                  {row.getVisibleCells().map((cell) => (
                    <TableCell key={cell.id}>
                      {cell.column.id === hierarchyId ? (
                        <span
                          className="zen-flex zen-items-center zen-gap-1"
                          /* Inline, not a utility: depth is unbounded, so no
                             finite class set can express it. Same reasoning as
                             Tree's indent. */
                          style={{ paddingInlineStart: row.depth * indent }}
                        >
                          {row.getCanExpand() ? (
                            <button
                              type="button"
                              // The row handles arrows; this button is the
                              // pointer affordance and must not also steal a tab
                              // stop from the roving row focus.
                              tabIndex={-1}
                              aria-hidden="true"
                              onClick={(e) => {
                                e.stopPropagation();
                                row.toggleExpanded();
                              }}
                              className="zen-inline-flex zen-w-4 zen-shrink-0 zen-items-center zen-justify-center zen-border-0 zen-bg-transparent zen-p-0 zen-cursor-pointer zen-text-zen-muted-fg"
                            >
                              <Icon
                                name="chevron-right"
                                size={14}
                                className={cn(
                                  "zen-transition-transform",
                                  row.getIsExpanded() && "zen-rotate-90",
                                )}
                              />
                            </button>
                          ) : (
                            <span className="zen-inline-block zen-w-4 zen-shrink-0" />
                          )}
                          {flexRender(cell.column.columnDef.cell, cell.getContext())}
                        </span>
                      ) : (
                        flexRender(cell.column.columnDef.cell, cell.getContext())
                      )}
                    </TableCell>
                  ))}
                </TableRow>
              );
            })
          )}
        </TableBody>
      </Table>
    </div>
  );
}

// packages/solid/src/components/tree-table/tree-table.tsx
import { For, Show, createMemo, createSignal, splitProps } from "solid-js";
import {
  createSolidTable,
  flexRender,
  getCoreRowModel,
  getExpandedRowModel,
  getFilteredRowModel,
  getSortedRowModel,
  type ColumnDef,
  type ExpandedState,
  type Row,
  type RowSelectionState,
  type SortingState,
} from "@tanstack/solid-table";
import { arrowStep } from "@algorisys/zen-ui-core";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../data-table/table";
import { Checkbox } from "../form/checkbox/checkbox";
import { Icon } from "../icon/icon";
import { Input } from "../form/input/input";
import { Button } from "../button/button";
import { cn } from "../../lib/cn";

/**
 * TreeTable — a table whose rows form a hierarchy.
 *
 *   <TreeTable data={accounts} columns={columns} />
 *
 * This is a separate component from `DataTable` rather than a mode of it, and
 * the reason is structural rather than a matter of size. Hierarchy and grouping
 * claim the SAME three slots in a TanStack table: `subRows`, the `expanded`
 * state, and the chevron column. DataTable's grouping synthesizes its group
 * rows *as* subRows, so a table cannot carry both a real hierarchy and a
 * grouped one — the second would nest inside the first and mean nothing. Adding
 * `getSubRows` to DataTable would therefore need a fifth mutual-exclusion gate
 * on top of the four it already has for virtualization, to describe a
 * combination nobody can use.
 *
 * What that buys, beyond avoiding a gate: the chevron lives INSIDE the first
 * column here, indented by depth, rather than in a leading gutter column the
 * way DataTable's `renderSubRow` toggle does. That is what makes the hierarchy
 * readable — you follow one column down the page. A gutter of chevrons at a
 * fixed offset tells you a row expands but not what it belongs to.
 *
 * Reach for `DataTable` for flat data with grouping, virtualization, pagination
 * and inline editing; reach for this when the data is genuinely nested and the
 * nesting is the point.
 */

/** The default child accessor: a `children` array, which is what nested JSON usually calls it. */
const defaultGetSubRows = <TData,>(row: TData): TData[] | undefined =>
  (row as { children?: TData[] }).children;

export interface TreeTableProps<TData, TValue = unknown> {
  data: TData[];
  columns: ColumnDef<TData, TValue>[];
  /**
   * Where a row's children live. Defaults to `row.children`.
   * Return `undefined` (not `[]`) for a leaf — an empty array still reads as
   * "expandable, but empty" and renders a chevron that does nothing.
   */
  getSubRows?: (row: TData) => TData[] | undefined;
  getRowId?: (originalRow: TData, index: number, parent?: Row<TData>) => string;

  /* expansion */
  expanded?: ExpandedState;
  /** `true` expands everything on first render. */
  defaultExpanded?: ExpandedState;
  onExpandedChange?: (state: ExpandedState) => void;
  /** Show the expand-all / collapse-all control. Default true. */
  enableExpandAll?: boolean;

  /* sorting — sorts within each parent's children, never across levels */
  enableSorting?: boolean;
  sorting?: SortingState;
  onSortingChange?: (state: SortingState) => void;

  /* filtering */
  enableGlobalFilter?: boolean;
  globalFilter?: string;
  onGlobalFilterChange?: (value: string) => void;
  globalFilterPlaceholder?: string;

  /* selection */
  enableRowSelection?: boolean;
  /** Selecting a parent selects its descendants. Default true. */
  enableSubRowSelection?: boolean;
  rowSelection?: RowSelectionState;
  onRowSelectionChange?: (state: RowSelectionState) => void;

  /* presentation */
  /** Which column carries the chevron. Defaults to the first visible column. */
  hierarchyColumnId?: string;
  /** Pixels of indent per level. Default 20. */
  indent?: number;
  stickyHeader?: boolean;
  headerVariant?: "plain" | "underline" | "branded";
  maxBodyHeight?: number;
  rowClassName?: (row: Row<TData>) => string | undefined;
  onRowClick?: (row: Row<TData>) => void;
  emptyMessage?: string;
  loading?: boolean;
  class?: string;
}

export function TreeTable<TData, TValue = unknown>(props: TreeTableProps<TData, TValue>) {
  const [local] = splitProps(props, ["class"]);

  const [expandedInner, setExpandedInner] = createSignal<ExpandedState>(props.defaultExpanded ?? {});
  const [sortingInner, setSortingInner] = createSignal<SortingState>([]);
  const [selectionInner, setSelectionInner] = createSignal<RowSelectionState>({});
  const [globalFilterInner, setGlobalFilterInner] = createSignal("");

  const expanded = () => props.expanded ?? expandedInner();
  const sorting = () => props.sorting ?? sortingInner();
  const selection = () => props.rowSelection ?? selectionInner();
  const globalFilter = () => props.globalFilter ?? globalFilterInner();

  const indent = () => props.indent ?? 20;

  /* The selection checkbox goes in its own leading column; the chevron does
   * NOT, because it belongs to the hierarchy column's text.
   *
   * eslint-disable solid/no-destructure -- same false positive DataTable
   * documents at its own `augmentedColumns`: these are TanStack ColumnDef
   * renderers destructuring a per-render context object, not Solid components
   * destructuring reactive props, and the rule cannot tell the two apart.
   */
  /* eslint-disable solid/no-destructure */
  const augmentedColumns = createMemo<ColumnDef<TData, TValue>[]>(() => {
    if (!props.enableRowSelection) return props.columns;
    const select: ColumnDef<TData, TValue> = {
      id: "__select__",
      header: ({ table }) => (
        <Checkbox
          checked={table.getIsAllRowsSelected()}
          indeterminate={!table.getIsAllRowsSelected() && table.getIsSomeRowsSelected()}
          onChange={(v: boolean) => table.toggleAllRowsSelected(v)}
          aria-label="Select all rows"
        />
      ),
      cell: ({ row }) => {
        /*
         * A parent's checkbox describes its SUBTREE, not its own row entry.
         * `getIsSelected()` alone is that entry, and TanStack never clears it
         * when a descendant is unticked — so a parent whose child you just
         * unticked would keep rendering "checked" while the row below it says
         * otherwise. Measured: tick Engineering, untick Infrastructure, and the
         * naive version leaves Engineering fully checked.
         */
        const hasChildren = () => row.subRows.length > 0;
        const checked = () =>
          hasChildren()
            ? row.getIsSelected() && row.getIsAllSubRowsSelected()
            : row.getIsSelected();
        const partial = () =>
          !checked() && (row.getIsSomeSelected() || (hasChildren() && row.getIsSelected()));
        return (
          <Checkbox
            checked={checked()}
            indeterminate={partial()}
            onChange={(v: boolean) => row.toggleSelected(v)}
            aria-label={`Select row ${row.index + 1}`}
          />
        );
      },
      enableSorting: false,
      enableHiding: false,
      size: 36,
    };
    return [select, ...props.columns];
  });
  /* eslint-enable solid/no-destructure */

  const table = createSolidTable<TData>({
    get data() {
      return props.data;
    },
    get columns() {
      return augmentedColumns() as ColumnDef<TData, unknown>[];
    },
    state: {
      get expanded() {
        return expanded();
      },
      get sorting() {
        return sorting();
      },
      get rowSelection() {
        return selection();
      },
      get globalFilter() {
        return globalFilter();
      },
    },
    get getSubRows() {
      return props.getSubRows ?? defaultGetSubRows;
    },
    get getRowId() {
      return props.getRowId;
    },
    get enableSorting() {
      return props.enableSorting ?? true;
    },
    get enableRowSelection() {
      return !!props.enableRowSelection;
    },
    get enableSubRowSelection() {
      return props.enableSubRowSelection ?? true;
    },
    /*
     * Filter from the leaves up, so a matching child keeps its ancestors on
     * screen. The default drops any row that does not match ITSELF, which for a
     * tree means a hit three levels down takes its whole path with it and the
     * user sees an empty table while the count says otherwise.
     */
    filterFromLeafRows: true,
    onExpandedChange: (updater) => {
      const next = typeof updater === "function" ? updater(expanded()) : updater;
      if (props.expanded === undefined) setExpandedInner(next);
      props.onExpandedChange?.(next);
    },
    onSortingChange: (updater) => {
      const next = typeof updater === "function" ? updater(sorting()) : updater;
      if (props.sorting === undefined) setSortingInner(next);
      props.onSortingChange?.(next);
    },
    onRowSelectionChange: (updater) => {
      const next = typeof updater === "function" ? updater(selection()) : updater;
      if (props.rowSelection === undefined) setSelectionInner(next);
      props.onRowSelectionChange?.(next);
    },
    onGlobalFilterChange: (updater) => {
      const next = typeof updater === "function" ? updater(globalFilter()) : updater;
      if (props.globalFilter === undefined) setGlobalFilterInner(next);
      props.onGlobalFilterChange?.(next);
    },
    getCoreRowModel: getCoreRowModel(),
    getExpandedRowModel: getExpandedRowModel(),
    get getSortedRowModel() {
      return (props.enableSorting ?? true) ? getSortedRowModel() : undefined;
    },
    get getFilteredRowModel() {
      return props.enableGlobalFilter ? getFilteredRowModel() : undefined;
    },
  });

  const rows = () => table.getRowModel().rows;

  /** The column the hierarchy reads down. */
  const hierarchyColumnId = () => {
    if (props.hierarchyColumnId) return props.hierarchyColumnId;
    return table.getVisibleLeafColumns().find((c) => !c.id.startsWith("__"))?.id;
  };

  /*
   * aria-posinset / aria-setsize are per-parent, not per-page: a treegrid row's
   * "set" is its siblings. TanStack's flat row model does not carry that, so it
   * is counted once per render rather than walked per row.
   */
  const siblingInfo = createMemo(() => {
    const info = new Map<string, { pos: number; size: number }>();
    const byParent = new Map<string, Row<TData>[]>();
    for (const row of rows()) {
      const key = row.parentId ?? "";
      const list = byParent.get(key);
      if (list) list.push(row);
      else byParent.set(key, [row]);
    }
    for (const list of byParent.values()) {
      list.forEach((row, i) => info.set(row.id, { pos: i + 1, size: list.length }));
    }
    return info;
  });

  /* ---- roving focus, the WAI-ARIA treegrid row pattern ---- */
  const rowRefs = new Map<string, HTMLTableRowElement>();
  const [focusedId, setFocusedId] = createSignal<string | null>(null);
  const activeId = () => focusedId() ?? rows()[0]?.id;

  const focusRow = (id: string | undefined | null) => {
    if (!id) return;
    setFocusedId(id);
    rowRefs.get(id)?.focus();
  };

  const moveBy = (from: Row<TData>, delta: number) => {
    const all = rows();
    const i = all.findIndex((r) => r.id === from.id);
    focusRow(all[i + delta]?.id);
  };

  const onRowKeyDown = (e: KeyboardEvent, row: Row<TData>) => {
    const step = arrowStep(e.key, e.currentTarget as Element);
    if (e.key === "ArrowDown") {
      e.preventDefault();
      moveBy(row, 1);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      moveBy(row, -1);
    } else if (step === 1) {
      // Forward: open a closed node, else descend into it.
      e.preventDefault();
      if (row.getCanExpand() && !row.getIsExpanded()) row.toggleExpanded(true);
      else if (row.getIsExpanded()) moveBy(row, 1);
    } else if (step === -1) {
      // Backward: close an open node, else climb to the parent.
      e.preventDefault();
      if (row.getIsExpanded()) row.toggleExpanded(false);
      else if (row.parentId) focusRow(row.parentId);
    } else if (e.key === "Home") {
      e.preventDefault();
      focusRow(rows()[0]?.id);
    } else if (e.key === "End") {
      e.preventDefault();
      focusRow(rows()[rows().length - 1]?.id);
    } else if (e.key === "Enter" || e.key === " ") {
      if (props.onRowClick) {
        e.preventDefault();
        props.onRowClick(row);
      } else if (row.getCanExpand()) {
        e.preventDefault();
        row.toggleExpanded();
      }
    }
  };

  const headerVariantRowClass = () =>
    props.headerVariant === "branded"
      ? "zen-bg-zen-primary-soft [&>th]:zen-text-zen-primary-soft-fg [&>th]:zen-font-semibold"
      : "";
  const headerVariantTheadClass = () =>
    props.headerVariant === "underline"
      ? "[&_tr:last-child]:zen-border-b-2 [&_tr:last-child]:zen-border-zen-primary"
      : "";
  const stickyRowClass = () =>
    props.stickyHeader
      ? props.headerVariant === "branded"
        ? "zen-sticky zen-top-0 zen-z-10"
        : "zen-sticky zen-top-0 zen-z-10 zen-bg-zen-background"
      : "";

  const showToolbar = () => props.enableGlobalFilter || (props.enableExpandAll ?? true);

  return (
    <div class={cn("zen-flex zen-w-full zen-flex-col zen-gap-3", local.class)}>
      <Show when={showToolbar()}>
        <div class="zen-flex zen-flex-wrap zen-items-center zen-gap-2">
          <Show when={props.enableGlobalFilter}>
            <Input
              value={globalFilter()}
              onInput={(e: { currentTarget: HTMLInputElement }) => table.setGlobalFilter(e.currentTarget.value)}
              placeholder={props.globalFilterPlaceholder ?? "Search…"}
              class="zen-max-w-xs"
              aria-label="Search"
            />
          </Show>
          <Show when={props.enableExpandAll ?? true}>
            <Button
              variant="outline"
              size="sm"
              onClick={() => table.toggleAllRowsExpanded()}
              aria-expanded={table.getIsAllRowsExpanded()}
            >
              <Icon
                name={table.getIsAllRowsExpanded() ? "chevron-down" : "chevron-right"}
                size={14}
              />
              {table.getIsAllRowsExpanded() ? "Collapse all" : "Expand all"}
            </Button>
          </Show>
        </div>
      </Show>

      <Table
        role="treegrid"
        aria-busy={props.loading || undefined}
        containerClass={props.maxBodyHeight ? "zen-overflow-auto" : undefined}
        containerStyle={
          props.maxBodyHeight ? { "max-height": `${props.maxBodyHeight}px` } : undefined
        }
      >
        <TableHeader class={headerVariantTheadClass()}>
          <For each={table.getHeaderGroups()}>
            {(group) => (
              <TableRow class={cn(headerVariantRowClass(), stickyRowClass())}>
                <For each={group.headers}>
                  {(header) => {
                    const sorted = () => header.column.getIsSorted();
                    return (
                      <TableHead
                        style={header.column.getSize() ? { width: `${header.getSize()}px` } : undefined}
                        aria-sort={
                          sorted() === "asc"
                            ? "ascending"
                            : sorted() === "desc"
                              ? "descending"
                              : header.column.getCanSort()
                                ? "none"
                                : undefined
                        }
                      >
                        <Show when={!header.isPlaceholder}>
                          <Show
                            when={header.column.getCanSort()}
                            fallback={flexRender(
                              header.column.columnDef.header,
                              header.getContext(),
                            )}
                          >
                            <button
                              type="button"
                              onClick={header.column.getToggleSortingHandler()}
                              class="zen-inline-flex zen-items-center zen-gap-1 zen-border-0 zen-bg-transparent zen-p-0 zen-font-inherit zen-text-inherit zen-cursor-pointer focus-visible:zen-outline-none focus-visible:zen-ring-2 focus-visible:zen-ring-zen-ring"
                            >
                              {flexRender(header.column.columnDef.header, header.getContext())}
                              <Show when={sorted()}>
                                <Icon
                                  name={sorted() === "asc" ? "chevron-up" : "chevron-down"}
                                  size={12}
                                />
                              </Show>
                            </button>
                          </Show>
                        </Show>
                      </TableHead>
                    );
                  }}
                </For>
              </TableRow>
            )}
          </For>
        </TableHeader>

        <TableBody>
          <Show
            when={!props.loading && rows().length > 0}
            fallback={
              <TableRow>
                <TableCell
                  colSpan={table.getVisibleLeafColumns().length}
                  class="zen-h-24 zen-text-center zen-text-zen-muted-fg"
                >
                  {props.loading ? "Loading…" : (props.emptyMessage ?? "No results.")}
                </TableCell>
              </TableRow>
            }
          >
            <For each={rows()}>
              {(row) => {
                const info = () => siblingInfo().get(row.id);
                return (
                  <TableRow
                    ref={(el: HTMLTableRowElement) => rowRefs.set(row.id, el)}
                    data-state={row.getIsSelected() ? "selected" : undefined}
                    data-depth={row.depth}
                    class={cn(
                      "focus-visible:zen-outline-none focus-visible:zen-ring-2 focus-visible:zen-ring-zen-ring focus-visible:zen-ring-inset",
                      props.onRowClick && "zen-cursor-pointer",
                      props.rowClassName?.(row),
                    )}
                    // aria-level is 1-based; TanStack's depth is 0-based.
                    aria-level={row.depth + 1}
                    aria-expanded={row.getCanExpand() ? row.getIsExpanded() : undefined}
                    aria-posinset={info()?.pos}
                    aria-setsize={info()?.size}
                    aria-selected={props.enableRowSelection ? row.getIsSelected() : undefined}
                    tabIndex={activeId() === row.id ? 0 : -1}
                    onFocus={() => setFocusedId(row.id)}
                    onKeyDown={(e) => onRowKeyDown(e, row)}
                    onClick={() => props.onRowClick?.(row)}
                  >
                    <For each={row.getVisibleCells()}>
                      {(cell) => (
                        <TableCell>
                          <Show
                            when={cell.column.id === hierarchyColumnId()}
                            fallback={flexRender(cell.column.columnDef.cell, cell.getContext())}
                          >
                            <span
                              class="zen-flex zen-items-center zen-gap-1"
                              /* Inline, not a utility: depth is unbounded, so no
                                 finite class set can express it. Same reasoning
                                 as Tree's indent. */
                              style={{ "padding-inline-start": `${row.depth * indent()}px` }}
                            >
                              <Show
                                when={row.getCanExpand()}
                                fallback={<span class="zen-inline-block zen-w-4 zen-shrink-0" />}
                              >
                                <button
                                  type="button"
                                  // The row handles arrows; this button is the
                                  // pointer affordance and must not also steal a
                                  // tab stop from the roving row focus.
                                  tabIndex={-1}
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    row.toggleExpanded();
                                  }}
                                  aria-hidden="true"
                                  class="zen-inline-flex zen-w-4 zen-shrink-0 zen-items-center zen-justify-center zen-border-0 zen-bg-transparent zen-p-0 zen-cursor-pointer zen-text-zen-muted-fg"
                                >
                                  <Icon
                                    name="chevron-right"
                                    size={14}
                                    class={cn(
                                      "zen-transition-transform",
                                      row.getIsExpanded() && "zen-rotate-90",
                                    )}
                                  />
                                </button>
                              </Show>
                              {flexRender(cell.column.columnDef.cell, cell.getContext())}
                            </span>
                          </Show>
                        </TableCell>
                      )}
                    </For>
                  </TableRow>
                );
              }}
            </For>
          </Show>
        </TableBody>
      </Table>
    </div>
  );
}
