// packages/react/src/components/combobox/combobox.tsx
import * as React from "react";
import { cn } from "../../lib/cn";
import { Button } from "../button/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "../popover/popover";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandLoading,
} from "./command";

/**
 * Combobox — searchable single-select with optional async option loading.
 * Built on cmdk (filtering + keyboard) + Radix Popover (positioning +
 * dismissal). Replaces Select when free-text search is needed across a
 * large or remote option set.
 *
 * Synchronous (in-memory):
 *
 *   <Combobox
 *     options={[{ value: "a", label: "Alpha" }, …]}
 *     value={picked}
 *     onValueChange={setPicked}
 *     placeholder="Pick one"
 *   />
 *
 * Async (server-driven):
 *
 *   <Combobox
 *     value={picked}
 *     onValueChange={setPicked}
 *     onSearch={async (query) => {
 *       const res = await fetch(`/api/options?q=${query}`);
 *       return res.json();
 *     }}
 *     debounceMs={250}
 *   />
 *
 * The async signature replaces `options`; the component handles
 * debounce, abort-on-stale, and loading / no-results states.
 *
 * Creatable (the option does not exist yet):
 *
 *   <Combobox
 *     options={tags}
 *     creatable
 *     onCreate={(label) => {
 *       const opt = { value: slug(label), label };
 *       setTags((prev) => [...prev, opt]);
 *       return opt;               // returned -> selected for you
 *     }}
 *   />
 *
 * The component never touches `options`: it cannot know where the list lives
 * or what a new option's `value` should be, so creating is always the
 * caller's. Selecting does not have to be. RETURN the new option and it is
 * selected; return nothing and the value is left alone for the caller to set.
 */

export interface ComboboxOption {
  value: string;
  label: string;
  /**
   * Rich row content, rendered INSTEAD of `label`.
   *
   * `label` stays the string: it is what the filter matches, what the trigger
   * shows once a value is picked, and what `creatable` compares against. This
   * is only what the row looks like — a second line of metadata, a highlighted
   * match, an avatar beside the name.
   */
  content?: React.ReactNode;
  /** Optional extra text used by cmdk's fuzzy match. */
  keywords?: string[];
  disabled?: boolean;
}

export interface ComboboxProps {
  /** Static option list (synchronous mode). Ignored if `onSearch` is provided. */
  options?: ComboboxOption[];
  /** Async loader (server-driven). Called on every input change, debounced. */
  onSearch?: (query: string) => Promise<ComboboxOption[]>;
  /** Selected value. Pass "" / null to clear. */
  value?: string;
  /** Defaults to "". */
  defaultValue?: string;
  onValueChange?: (value: string, option: ComboboxOption | null) => void;
  /** Text shown when no value is selected. */
  placeholder?: string;
  /** Placeholder inside the search input. */
  searchPlaceholder?: string;
  /** Message when the result list is empty after filtering / search. */
  emptyMessage?: string;
  /** Async-mode: ms to wait after the last keystroke before calling onSearch. */
  debounceMs?: number;
  /**
   * Offer to create the typed text when it matches no option's label.
   * Needs `onCreate` to do anything.
   */
  creatable?: boolean;
  /**
   * Called with the typed text when the create row is chosen. Adding the
   * option to your list is always yours — the component cannot know where the
   * list lives or what a new `value` should be.
   *
   * RETURN the new option and it is selected for you. Return nothing and the
   * value is left alone, so a caller who wants to select it later (after a
   * round trip to a server, say) stays in control. Both are supported on
   * purpose; returning is just the short path.
   */
  onCreate?: (label: string) => ComboboxOption | void;
  /** Verb on the create row — `Create "foo"`. Default "Create". */
  createLabel?: string;
  /** Trigger button's width. Defaults to 240. */
  width?: number | string;
  disabled?: boolean;
  className?: string;
}

const Combobox: React.FC<ComboboxProps> = ({
  options,
  onSearch,
  value,
  defaultValue,
  onValueChange,
  placeholder = "Select…",
  searchPlaceholder = "Search…",
  emptyMessage = "No results.",
  debounceMs = 250,
  creatable,
  onCreate,
  createLabel = "Create",
  width = 240,
  disabled,
  className,
}) => {
  const isAsync = typeof onSearch === "function";

  const [internalValue, setInternalValue] = React.useState(defaultValue ?? "");
  const isControlled = value !== undefined;
  const selected = isControlled ? (value as string) : internalValue;

  const [open, setOpen] = React.useState(false);
  const [query, setQuery] = React.useState("");

  // Async-mode state
  const [asyncResults, setAsyncResults] = React.useState<ComboboxOption[]>([]);
  const [asyncLoading, setAsyncLoading] = React.useState(false);
  const abortRef = React.useRef<AbortController | null>(null);
  const seqRef = React.useRef(0);

  // Trigger fresh fetch when input changes (async mode)
  React.useEffect(() => {
    if (!isAsync) return;
    if (!open) return;

    const seq = ++seqRef.current;
    abortRef.current?.abort();
    const ac = new AbortController();
    abortRef.current = ac;

    const t = setTimeout(async () => {
      setAsyncLoading(true);
      try {
        const results = await onSearch!(query);
        if (seq === seqRef.current && !ac.signal.aborted) {
          setAsyncResults(results);
        }
      } catch {
        if (seq === seqRef.current && !ac.signal.aborted) {
          setAsyncResults([]);
        }
      } finally {
        if (seq === seqRef.current && !ac.signal.aborted) {
          setAsyncLoading(false);
        }
      }
    }, debounceMs);

    return () => {
      clearTimeout(t);
      ac.abort();
    };
  }, [query, open, isAsync, onSearch, debounceMs]);

  // Track the currently-selected option's label for the trigger
  // useMemo, not a bare expression: `options ?? []` allocates a NEW array on
  // every render when `options` is undefined, so every hook depending on
  // allOptions re-ran each time even when nothing had changed.
  const allOptions = React.useMemo(
    () => (isAsync ? asyncResults : options ?? []),
    [isAsync, asyncResults, options],
  );
  const selectedOption = React.useMemo(
    () => allOptions.find((o) => o.value === selected) ?? null,
    [allOptions, selected],
  );
  // Keep last-known label for selected values that aren't in the current
  // async result page (so the trigger doesn't read "Select…" when the
  // dropdown re-renders with a fresh search).
  const lastLabelRef = React.useRef<string>("");
  if (selectedOption) lastLabelRef.current = selectedOption.label;

  const triggerLabel =
    selected && lastLabelRef.current
      ? lastLabelRef.current
      : placeholder;

  const update = (next: string, opt: ComboboxOption | null) => {
    if (!isControlled) setInternalValue(next);
    onValueChange?.(next, opt);
  };

  // Compared against the LABEL, not the value: the user is typing what they
  // read, and "already exists" has to mean the same thing to them as to us.
  const typed = query.trim();
  const alreadyExists = allOptions.some(
    (o) => o.label.trim().toLowerCase() === typed.toLowerCase(),
  );
  const showCreate = Boolean(creatable && onCreate) && typed.length > 0 && !alreadyExists;

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          color="neutral"
          role="combobox"
          aria-expanded={open}
          disabled={disabled}
          className={cn(
            "zen-justify-between zen-font-normal",
            !selected && "zen-text-zen-muted-fg",
            className,
          )}
          style={{ width }}
          iconRight={<ChevronIcon />}
        >
          <span style={{ overflow: "hidden", textOverflow: "ellipsis" }}>
            {triggerLabel}
          </span>
        </Button>
      </PopoverTrigger>
      <PopoverContent
        className="zen-p-0"
        style={{ width: typeof width === "number" ? width : undefined }}
        align="start"
      >
        <Command
          // In async mode we already filter server-side, so disable cmdk's
          // built-in filter (otherwise it re-filters the already-filtered list).
          shouldFilter={!isAsync}
        >
          <CommandInput
            value={query}
            onValueChange={setQuery}
            placeholder={searchPlaceholder}
          />
          <CommandList>
            {isAsync && asyncLoading ? (
              <CommandLoading>Searching…</CommandLoading>
            ) : null}
            {/* CommandEmpty only shows when nothing matches. With a create row
                present that is exactly when it is NOT empty — you get
                "Create foo" instead of "No results", which is the point. */}
            <CommandEmpty>{emptyMessage}</CommandEmpty>
            <CommandGroup>
              {allOptions.map((o) => (
                <CommandItem
                  key={o.value}
                  value={o.value}
                  keywords={[o.label, ...(o.keywords ?? [])]}
                  disabled={o.disabled}
                  onSelect={(v) => {
                    if (o.disabled) return;
                    const next = v === selected ? "" : v;
                    const nextOpt =
                      next === ""
                        ? null
                        : allOptions.find((x) => x.value === next) ?? null;
                    update(next, nextOpt);
                    setOpen(false);
                  }}
                >
                  <CheckIcon
                    style={{
                      opacity: selected === o.value ? 1 : 0,
                      marginRight: 6,
                    }}
                  />
                  <span style={{ flex: 1 }}>{o.content ?? o.label}</span>
                </CommandItem>
              ))}
            </CommandGroup>
            {showCreate ? (
              <CommandGroup>
                <CommandItem
                  // The typed text is a keyword so cmdk's filter always keeps
                  // this row: a create row that filters itself out is useless
                  // exactly when it is needed.
                  value={`__create__${typed}`}
                  keywords={[typed]}
                  onSelect={() => {
                    const created = onCreate!(typed);
                    if (created) {
                      // Cache the label before selecting: the caller's options
                      // update has not landed yet, so the trigger would look
                      // this value up, miss, and fall back to the placeholder.
                      lastLabelRef.current = created.label;
                      update(created.value, created);
                    }
                    setQuery("");
                    setOpen(false);
                  }}
                >
                  <PlusIcon style={{ marginRight: 6 }} />
                  <span style={{ flex: 1 }}>
                    {createLabel} “{typed}”
                  </span>
                </CommandItem>
              </CommandGroup>
            ) : null}
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
};

const ChevronIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
    <polyline points="6 9 12 15 18 9" />
  </svg>
);

const PlusIcon: React.FC<{ style?: React.CSSProperties }> = ({ style }) => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden style={style}>
    <line x1="12" y1="5" x2="12" y2="19" />
    <line x1="5" y1="12" x2="19" y2="12" />
  </svg>
);

const CheckIcon: React.FC<{ style?: React.CSSProperties }> = ({ style }) => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden style={style}>
    <polyline points="20 6 9 17 4 12" />
  </svg>
);

export { Combobox };

// packages/solid/src/components/combobox/combobox.tsx
import {
  type JSX,
  Show,
  createEffect,
  createMemo,
  createSignal,
  splitProps,
} from "solid-js";
import { Combobox as KCombobox } from "@kobalte/core/combobox";
import { cn } from "../../lib/cn";

/**
 * Combobox — searchable single-select built on Kobalte Combobox.
 *
 * Sync (in-memory):
 *
 *   <Combobox
 *     options={[{ value: "a", label: "Alpha" }, …]}
 *     value={picked()}
 *     onValueChange={setPicked}
 *   />
 *
 * Async (server-driven):
 *
 *   <Combobox
 *     value={picked()}
 *     onValueChange={setPicked}
 *     onSearch={async (q) => { const r = await fetch(...); return r.json(); }}
 *     debounceMs={250}
 *   />
 *
 * API delta from the React (cmdk) binding: filtering is provided by
 * Kobalte's built-in default text filter for sync mode, or by your
 * onSearch loader for async mode. The shape `{value, label, keywords}`
 * is the same.
 */

export interface ComboboxOption {
  value: string;
  label: string;
  /**
   * Rich row content, rendered INSTEAD of `label`.
   *
   * `label` stays the string: it is what the filter matches, what the trigger
   * shows once a value is picked, and what `creatable` compares against. This
   * is only what the row looks like — a second line of metadata, a highlighted
   * match, an avatar beside the name.
   */
  content?: JSX.Element;
  keywords?: string[];
  disabled?: boolean;
}

export type ComboboxProps = {
  options?: ComboboxOption[];
  onSearch?: (query: string) => Promise<ComboboxOption[]>;
  value?: string;
  defaultValue?: string;
  onValueChange?: (value: string, option: ComboboxOption | null) => void;
  placeholder?: string;
  searchPlaceholder?: string;
  emptyMessage?: string;
  debounceMs?: number;
  /**
   * Offer to create the typed text when it matches no option's label.
   * Needs `onCreate` to do anything.
   */
  creatable?: boolean;
  /**
   * Called with the typed text when the create row is chosen. Adding the
   * option to your list is always yours — the component cannot know where the
   * list lives or what a new `value` should be.
   *
   * RETURN the new option and it is selected for you. Return nothing and the
   * value is left alone, so a caller who wants to select it later (after a
   * round trip to a server, say) stays in control. Both are supported on
   * purpose; returning is just the short path.
   */
  onCreate?: (label: string) => ComboboxOption | void;
  /** Verb on the create row — `Create "foo"`. Default "Create". */
  createLabel?: string;
  width?: number | string;
  disabled?: boolean;
  class?: string;
};

/**
 * Kobalte builds the listbox from `options`, so the create row is a synthetic
 * OPTION rather than a button under the list — that keeps it arrow-navigable
 * and selectable with Enter like every other row. React reaches the same place
 * through a cmdk item; the mechanism differs, the behaviour does not.
 */
const CREATE_SENTINEL = "__zen_create__";

export const Combobox = (rawProps: ComboboxProps) => {
  const [props] = splitProps(rawProps, [
    "options",
    "onSearch",
    "value",
    "defaultValue",
    "onValueChange",
    "placeholder",
    "searchPlaceholder",
    "emptyMessage",
    "debounceMs",
    "creatable",
    "onCreate",
    "createLabel",
    "width",
    "disabled",
    "class",
  ]);

  const isAsync = () => typeof props.onSearch === "function";
  const [asyncOptions, setAsyncOptions] = createSignal<ComboboxOption[]>([]);
  const [asyncLoading, setAsyncLoading] = createSignal(false);
  let debounceTimer: ReturnType<typeof setTimeout> | undefined;
  let lastQueryToken = 0;

  const [query, setQuery] = createSignal("");

  const baseOptions = createMemo<ComboboxOption[]>(() => {
    if (isAsync()) return asyncOptions();
    return props.options ?? [];
  });

  // Compared against the LABEL, not the value: the user is typing what they
  // read, and "already exists" has to mean the same thing to them as to us.
  const typed = () => query().trim();
  const showCreate = createMemo(
    () =>
      Boolean(props.creatable && props.onCreate) &&
      typed().length > 0 &&
      !baseOptions().some((o) => o.label.trim().toLowerCase() === typed().toLowerCase()),
  );

  const effectiveOptions = createMemo<ComboboxOption[]>(() =>
    showCreate()
      ? [
          ...baseOptions(),
          {
            value: CREATE_SENTINEL,
            label: `${props.createLabel ?? "Create"} “${typed()}”`,
          },
        ]
      : baseOptions(),
  );

  const runSearch = (q: string) => {
    if (!props.onSearch) return;
    const token = ++lastQueryToken;
    setAsyncLoading(true);
    void props
      .onSearch(q)
      .then((res) => {
        if (token !== lastQueryToken) return;
        setAsyncOptions(res);
      })
      .finally(() => {
        if (token === lastQueryToken) setAsyncLoading(false);
      });
  };

  const onInputChange = (q: string) => {
    // Tracked in both modes now: `creatable` needs the typed text to know
    // whether to offer it, and that is not an async-only concern.
    setQuery(q);
    if (!isAsync()) return;
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => runSearch(q), props.debounceMs ?? 250);
  };

  createEffect(() => {
    if (isAsync()) runSearch("");
  });

  const isControlled = () => props.value !== undefined;
  const [internalValue, setInternalValue] = createSignal<string>(
    props.defaultValue ?? "",
  );
  const selectedValue = createMemo<string>(() =>
    isControlled() ? (props.value as string) : internalValue(),
  );
  const selectedOption = createMemo<ComboboxOption | null>(() => {
    const v = selectedValue();
    return effectiveOptions().find((o) => o.value === v) ?? null;
  });

  return (
    <KCombobox<ComboboxOption>
      options={effectiveOptions()}
      optionValue="value"
      optionTextValue="label"
      optionLabel="label"
      optionDisabled="disabled"
      value={selectedOption()}
      onChange={(opt) => {
        // The create row is not a selection: hand the text back and leave the
        // value alone, or the sentinel becomes the answer.
        if (opt?.value === CREATE_SENTINEL) {
          const created = props.onCreate?.(typed());
          setQuery("");
          if (created) {
            if (!isControlled()) setInternalValue(created.value);
            props.onValueChange?.(created.value, created);
          }
          return;
        }
        const next = opt?.value ?? "";
        if (!isControlled()) setInternalValue(next);
        props.onValueChange?.(next, opt);
      }}
      onInputChange={onInputChange}
      disabled={props.disabled}
      placeholder={props.placeholder ?? "Select…"}
      itemComponent={(itemProps) => (
        <KCombobox.Item
          item={itemProps.item}
          class={cn(
            "zen-relative zen-flex zen-cursor-default zen-select-none zen-items-center zen-rounded-zen-sm zen-py-1.5 zen-pl-8 zen-pr-2 zen-text-sm zen-outline-none",
            "data-[highlighted]:zen-bg-zen-muted",
            "data-[disabled]:zen-pointer-events-none data-[disabled]:zen-opacity-50",
          )}
        >
          <KCombobox.ItemIndicator class="zen-absolute zen-start-2 zen-flex zen-h-3.5 zen-w-3.5 zen-items-center zen-justify-center">
            <CheckIcon />
          </KCombobox.ItemIndicator>
          <KCombobox.ItemLabel>
            {itemProps.item.rawValue.content ?? itemProps.item.rawValue.label}
          </KCombobox.ItemLabel>
        </KCombobox.Item>
      )}
      class={props.class}
    >
      <KCombobox.Control<ComboboxOption>
        class={cn(
          "zen-inline-flex zen-items-center zen-gap-2 zen-h-10 zen-px-3",
          "zen-rounded-zen-md zen-border zen-border-zen-border zen-bg-zen-background",
          "focus-within:zen-outline-none focus-within:zen-ring-2 focus-within:zen-ring-zen-ring focus-within:zen-ring-offset-2",
        )}
        style={{ width: typeof props.width === "number" ? `${props.width}px` : (props.width ?? "240px") }}
      >
        <KCombobox.Input
          class="zen-flex-1 zen-min-w-0 zen-bg-transparent zen-border-0 zen-outline-none zen-text-sm placeholder:zen-text-zen-muted-fg"
          placeholder={props.searchPlaceholder ?? "Search…"}
        />
        <KCombobox.Trigger class="zen-bg-transparent zen-border-0 zen-cursor-pointer zen-text-zen-muted-fg">
          <KCombobox.Icon>
            <ChevronDown />
          </KCombobox.Icon>
        </KCombobox.Trigger>
      </KCombobox.Control>
      <KCombobox.Portal>
        <KCombobox.Content
          class={cn(
            "zen-z-50 zen-min-w-44 zen-overflow-hidden zen-rounded-zen-md zen-border zen-bg-zen-background zen-p-1 zen-text-zen-foreground zen-shadow-md",
          )}
        >
          <Show when={asyncLoading()}>
            <div class="zen-py-1.5 zen-px-2 zen-text-sm zen-text-zen-muted-fg">Loading…</div>
          </Show>
          <KCombobox.Listbox class="zen-max-h-72 zen-overflow-y-auto" />
          <Show when={effectiveOptions().length === 0 && !asyncLoading()}>
            <div class="zen-py-1.5 zen-px-2 zen-text-sm zen-text-zen-muted-fg">
              {props.emptyMessage ?? "No results."}
            </div>
          </Show>
        </KCombobox.Content>
      </KCombobox.Portal>
    </KCombobox>
  );
};

const ChevronDown = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden>
    <polyline points="6 9 12 15 18 9" />
  </svg>
);
const CheckIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <polyline points="20 6 9 17 4 12" />
  </svg>
);
