// packages/solid/src/App.tsx
import type { Component, ParentProps } from "solid-js";
import { For } from "solid-js";
import { A } from "@solidjs/router";
import { useTheme } from "./lib/theme";

/**
 * App shell — sidebar nav + a slot for the active route. Mirrors the
 * packages/react demo layout so the two bindings can be compared
 * side-by-side. New components are added by editing NAV below and
 * registering the corresponding <Route> in main.tsx.
 */

type NavGroup = {
  group: string;
  items: { label: string; path: string }[];
};

const NAV: NavGroup[] = [
  {
    group: "Primitives",
    items: [
      { label: "Button", path: "/button" },
      { label: "Badge", path: "/badge" },
      { label: "Card", path: "/card" },
      { label: "Skeleton", path: "/skeleton" },
      { label: "Loading", path: "/loading" },
      { label: "FAB", path: "/fab" },
      { label: "Separator", path: "/separator" },
    ],
  },
  {
    group: "Surfaces",
    items: [
      { label: "Alert", path: "/alert" },
      { label: "Banner", path: "/banner" },
      { label: "EmptyState", path: "/empty-state" },
    ],
  },
  {
    group: "Flows",
    items: [
      { label: "Stepper", path: "/stepper" },
    ],
  },
  {
    group: "Survey",
    items: [
      { label: "Rating", path: "/rating" },
      { label: "NPS", path: "/nps" },
      { label: "Likert", path: "/likert" },
    ],
  },
  {
    group: "Display (Kobalte)",
    items: [
      { label: "Avatar", path: "/avatar" },
      { label: "Progress", path: "/progress" },
      { label: "Tooltip", path: "/tooltip" },
    ],
  },
  {
    group: "Form (Kobalte)",
    items: [
      { label: "Switch", path: "/switch" },
      { label: "Checkbox", path: "/checkbox" },
      { label: "RadioGroup", path: "/radio-group" },
      { label: "Slider", path: "/slider" },
      { label: "Select", path: "/select" },
    ],
  },
  {
    group: "Disclosure (Kobalte)",
    items: [
      { label: "Tabs", path: "/tabs" },
      { label: "Accordion", path: "/accordion" },
    ],
  },
  {
    group: "Overlays (Kobalte)",
    items: [
      { label: "Popover", path: "/popover" },
      { label: "Dialog", path: "/dialog" },
      { label: "Sheet", path: "/sheet" },
      { label: "DropdownMenu", path: "/dropdown-menu" },
      { label: "Toast", path: "/toast" },
    ],
  },
  {
    group: "Layout",
    items: [
      { label: "ScrollArea", path: "/scroll-area" },
    ],
  },
  {
    group: "Form (custom)",
    items: [
      { label: "Input", path: "/input" },
      { label: "NumberField", path: "/number-field" },
      { label: "TagInput", path: "/tag-input" },
      { label: "PhoneInput", path: "/phone-input" },
      { label: "InputOTP", path: "/otp" },
      { label: "FileUpload", path: "/file-upload" },
    ],
  },
  {
    group: "Data",
    items: [
      { label: "DataTable", path: "/data-table" },
      { label: "Combobox", path: "/combobox" },
      { label: "MultiCombobox", path: "/multi-combobox" },
      { label: "VirtualizedItems", path: "/lazy-options" },
    ],
  },
];

const App: Component<ParentProps> = (props) => {
  const { theme, setTheme, themes } = useTheme();
  return (
    <div class="min-h-full flex bg-zen-background text-zen-foreground">
      <aside class="w-60 shrink-0 border-r border-zen-border p-4 flex flex-col gap-4">
        <div>
          <div class="text-lg font-semibold">Zen UI · Solid</div>
          <div class="text-xs text-zen-muted-fg">@algorisys/zen-ui-solid</div>
        </div>

        <label class="text-xs flex flex-col gap-1">
          <span class="text-zen-muted-fg">Theme</span>
          <select
            class="rounded-zen-md border border-zen-border px-2 py-1 text-sm bg-zen-background"
            value={theme()}
            onChange={(e) => setTheme(e.currentTarget.value as never)}
          >
            <For each={themes}>
              {(t) => <option value={t.name}>{t.label}</option>}
            </For>
          </select>
        </label>

        <nav class="flex flex-col gap-4 mt-2">
          <For each={NAV}>
            {(group) => (
              <div>
                <div class="text-xs uppercase tracking-wide text-zen-muted-fg mb-1">
                  {group.group}
                </div>
                <ul class="flex flex-col gap-0.5">
                  <For each={group.items}>
                    {(item) => (
                      <li>
                        <A
                          href={item.path}
                          class="block px-2 py-1.5 rounded-zen-sm text-sm text-zen-foreground hover:bg-zen-muted"
                          activeClass="bg-zen-primary-soft text-zen-primary-soft-fg"
                          end
                        >
                          {item.label}
                        </A>
                      </li>
                    )}
                  </For>
                </ul>
              </div>
            )}
          </For>
        </nav>
      </aside>

      <main class="flex-1 p-8 overflow-x-hidden">{props.children}</main>
    </div>
  );
};

export default App;

// src/App.tsx
import { useState } from "react";
import "./App.css";
import { NavLink, Routes, Route } from "react-router-dom";

import Welcome from "./components/Welcome";
import ThemeSwitcher from "./components/theme-switcher";

import NewButtonDemo from "./components/NewButtonDemo";
import NewTooltipDemo from "./components/NewTooltipDemo";
import NewDropdownMenuDemo from "./components/NewDropdownMenuDemo";
import NewSeparatorDemo from "./components/NewSeparatorDemo";
import NewSwitchDemo from "./components/NewSwitchDemo";
import NewCheckboxDemo from "./components/NewCheckboxDemo";
import NewRadioGroupDemo from "./components/NewRadioGroupDemo";
import NewProgressDemo from "./components/NewProgressDemo";
import NewAvatarDemo from "./components/NewAvatarDemo";
import NewBadgeDemo from "./components/NewBadgeDemo";
import NewSkeletonDemo from "./components/NewSkeletonDemo";
import NewLoadingDemo from "./components/NewLoadingDemo";
import NewSelectDemo from "./components/NewSelectDemo";
import NewSliderDemo from "./components/NewSliderDemo";
import NewScrollAreaDemo from "./components/NewScrollAreaDemo";
import NewInputDemo from "./components/NewInputDemo";
import NewNumberFieldDemo from "./components/NewNumberFieldDemo";
import NewDatePickerDemo from "./components/NewDatePickerDemo";
import NewOTPDemo from "./components/NewOTPDemo";
import NewPhoneInputDemo from "./components/NewPhoneInputDemo";
import NewFABDemo from "./components/NewFABDemo";
import NewFormDemo from "./components/NewFormDemo";
import NewDataTableDemo from "./components/NewDataTableDemo";
import NewLazyOptionsDemo from "./components/NewLazyOptionsDemo";
import NewComboboxDemo from "./components/NewComboboxDemo";
import NewAlertDemo from "./components/NewAlertDemo";
import NewDialogDemo from "./components/NewDialogDemo";
import NewToastDemo from "./components/NewToastDemo";
import NewFileUploadDemo from "./components/NewFileUploadDemo";
import NewBoundFieldsDemo from "./components/NewBoundFieldsDemo";
import NewStepperDemo from "./components/NewStepperDemo";
import NewBannerDemo from "./components/NewBannerDemo";
import NewEmptyStateDemo from "./components/NewEmptyStateDemo";
import NewTabsDemo from "./components/NewTabsDemo";
import NewAccordionDemo from "./components/NewAccordionDemo";
import NewCardDemo from "./components/NewCardDemo";
import NewSheetDemo from "./components/NewSheetDemo";
import NewDateRangePickerDemo from "./components/NewDateRangePickerDemo";
import NewTagInputDemo from "./components/NewTagInputDemo";
import NewMultiComboboxDemo from "./components/NewMultiComboboxDemo";
import NewRatingDemo from "./components/NewRatingDemo";
import NewNpsDemo from "./components/NewNpsDemo";
import NewLikertDemo from "./components/NewLikertDemo";
import NewTimePickerDemo from "./components/NewTimePickerDemo";
import NewDateTimePickerDemo from "./components/NewDateTimePickerDemo";
import { Toaster } from "./components/toast/toaster";

/**
 * Navigation data — single source of truth for the sidebar.
 * Add a new component's route here and it shows up under the right group.
 */
type NavEntry = { to: string; label: string };
type NavGroup = { title: string; items: NavEntry[] };

const NAV: NavGroup[] = [
  {
    title: "Getting started",
    items: [{ to: "/", label: "Welcome" }],
  },
  {
    title: "Components",
    items: [
      { to: "/button-new", label: "Button" },
      { to: "/tooltip-new", label: "Tooltip" },
      { to: "/dropdown-menu", label: "DropdownMenu" },
      { to: "/separator", label: "Separator" },
      { to: "/switch-new", label: "Switch" },
      { to: "/checkbox-new", label: "Checkbox" },
      { to: "/radio-group", label: "RadioGroup" },
      { to: "/progress-new", label: "Progress" },
      { to: "/avatar-new", label: "Avatar" },
      { to: "/badge-new", label: "Badge" },
      { to: "/skeleton-new", label: "Skeleton" },
      { to: "/loading-new", label: "Loading" },
      { to: "/select-new", label: "Select" },
      { to: "/slider-new", label: "Slider" },
      { to: "/scroll-area-new", label: "ScrollArea" },
      { to: "/input-new", label: "Input + Textarea" },
      { to: "/number-field-new", label: "NumberField" },
      { to: "/date-picker-new", label: "DatePicker" },
      { to: "/otp-new", label: "InputOTP" },
      { to: "/phone-input-new", label: "PhoneInput" },
      { to: "/fab-new", label: "FAB" },
      { to: "/form-new", label: "Form (RHF + Zod)" },
      { to: "/data-table", label: "DataTable" },
      { to: "/lazy-options", label: "Lazy options" },
      { to: "/combobox", label: "Combobox + Async" },
      { to: "/alert", label: "Alert" },
      { to: "/dialog", label: "Dialog + AlertDialog" },
      { to: "/toast", label: "Toast" },
      { to: "/file-upload", label: "FileUpload" },
      { to: "/form-bound", label: "Bound* fields" },
      { to: "/stepper", label: "Stepper" },
      { to: "/banner", label: "Banner" },
      { to: "/empty-state", label: "EmptyState" },
      { to: "/tabs", label: "Tabs" },
      { to: "/accordion", label: "Accordion" },
      { to: "/card", label: "Card" },
      { to: "/sheet", label: "Sheet / Drawer" },
      { to: "/date-range-picker", label: "DateRangePicker" },
      { to: "/tag-input", label: "TagInput" },
      { to: "/multi-combobox", label: "MultiCombobox" },
      { to: "/rating", label: "Rating" },
      { to: "/nps", label: "NPS" },
      { to: "/likert", label: "Likert" },
      { to: "/time-picker", label: "TimePicker" },
      { to: "/date-time-picker", label: "DateTimePicker" },
    ],
  },
];

const Sidebar: React.FC<{ collapsed: boolean }> = ({ collapsed }) => (
  <aside className={`sidebar${collapsed ? " is-collapsed" : ""}`} aria-hidden={collapsed}>
    {NAV.map((group) => (
      <div key={group.title} className="sidebar-group">
        <h4 className="sidebar-group-title">{group.title}</h4>
        <ul className="sidebar-list">
          {group.items.map((item) => (
            <li key={item.to}>
              <NavLink
                to={item.to}
                end={item.to === "/"}
                className={({ isActive }) =>
                  isActive
                    ? "sidebar-link sidebar-link-active"
                    : "sidebar-link sidebar-link-inactive"
                }
              >
                {item.label}
              </NavLink>
            </li>
          ))}
        </ul>
      </div>
    ))}
  </aside>
);

const SidebarToggle: React.FC<{
  collapsed: boolean;
  onToggle: () => void;
}> = ({ collapsed, onToggle }) => (
  <button
    type="button"
    className="sidebar-toggle"
    onClick={onToggle}
    aria-label={collapsed ? "Open sidebar" : "Close sidebar"}
    aria-expanded={!collapsed}
  >
    <svg
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <line x1="3" y1="6" x2="21" y2="6" />
      <line x1="3" y1="12" x2="21" y2="12" />
      <line x1="3" y1="18" x2="21" y2="18" />
    </svg>
  </button>
);

const SIDEBAR_KEY = "zen-sidebar-collapsed";

const App: React.FC = () => {
  const [collapsed, setCollapsed] = useState<boolean>(() => {
    if (typeof window === "undefined") return false;
    try {
      return window.localStorage.getItem(SIDEBAR_KEY) === "1";
    } catch {
      return false;
    }
  });
  const toggleSidebar = () => {
    setCollapsed((prev) => {
      const next = !prev;
      try {
        window.localStorage.setItem(SIDEBAR_KEY, next ? "1" : "0");
      } catch {
        /* ignore quota */
      }
      return next;
    });
  };

  return (
    <div className="app-shell">
      <header className="app-header">
        <div className="app-header-left">
          <SidebarToggle collapsed={collapsed} onToggle={toggleSidebar} />
          <div className="app-header-text">
            <h1 className="app-title">Zen UI Component Library</h1>
            <p className="app-subtitle">
              shadcn / Radix-style React component library by Algorisys.
            </p>
          </div>
        </div>
        <div className="app-header-actions">
          <ThemeSwitcher />
        </div>
      </header>
      <div className="app-body">
        <Sidebar collapsed={collapsed} />
        <main className="app-content">
          <Routes>
            <Route path="/" element={<Welcome />} />

            <Route path="/button-new" element={<NewButtonDemo />} />
            <Route path="/tooltip-new" element={<NewTooltipDemo />} />
            <Route path="/dropdown-menu" element={<NewDropdownMenuDemo />} />
            <Route path="/separator" element={<NewSeparatorDemo />} />
            <Route path="/switch-new" element={<NewSwitchDemo />} />
            <Route path="/checkbox-new" element={<NewCheckboxDemo />} />
            <Route path="/radio-group" element={<NewRadioGroupDemo />} />
            <Route path="/progress-new" element={<NewProgressDemo />} />
            <Route path="/avatar-new" element={<NewAvatarDemo />} />
            <Route path="/badge-new" element={<NewBadgeDemo />} />
            <Route path="/skeleton-new" element={<NewSkeletonDemo />} />
            <Route path="/loading-new" element={<NewLoadingDemo />} />
            <Route path="/select-new" element={<NewSelectDemo />} />
            <Route path="/slider-new" element={<NewSliderDemo />} />
            <Route path="/scroll-area-new" element={<NewScrollAreaDemo />} />
            <Route path="/input-new" element={<NewInputDemo />} />
            <Route path="/number-field-new" element={<NewNumberFieldDemo />} />
            <Route path="/date-picker-new" element={<NewDatePickerDemo />} />
            <Route path="/otp-new" element={<NewOTPDemo />} />
            <Route path="/phone-input-new" element={<NewPhoneInputDemo />} />
            <Route path="/fab-new" element={<NewFABDemo />} />
            <Route path="/form-new" element={<NewFormDemo />} />
            <Route path="/data-table" element={<NewDataTableDemo />} />
            <Route path="/lazy-options" element={<NewLazyOptionsDemo />} />
            <Route path="/combobox" element={<NewComboboxDemo />} />
            <Route path="/alert" element={<NewAlertDemo />} />
            <Route path="/dialog" element={<NewDialogDemo />} />
            <Route path="/toast" element={<NewToastDemo />} />
            <Route path="/file-upload" element={<NewFileUploadDemo />} />
            <Route path="/form-bound" element={<NewBoundFieldsDemo />} />
            <Route path="/stepper" element={<NewStepperDemo />} />
            <Route path="/banner" element={<NewBannerDemo />} />
            <Route path="/empty-state" element={<NewEmptyStateDemo />} />
            <Route path="/tabs" element={<NewTabsDemo />} />
            <Route path="/accordion" element={<NewAccordionDemo />} />
            <Route path="/card" element={<NewCardDemo />} />
            <Route path="/sheet" element={<NewSheetDemo />} />
            <Route path="/date-range-picker" element={<NewDateRangePickerDemo />} />
            <Route path="/tag-input" element={<NewTagInputDemo />} />
            <Route path="/multi-combobox" element={<NewMultiComboboxDemo />} />
            <Route path="/rating" element={<NewRatingDemo />} />
            <Route path="/nps" element={<NewNpsDemo />} />
            <Route path="/likert" element={<NewLikertDemo />} />
            <Route path="/time-picker" element={<NewTimePickerDemo />} />
            <Route path="/date-time-picker" element={<NewDateTimePickerDemo />} />
          </Routes>
        </main>
      </div>
      {/* Mounted once near the root so toast({...}) can be called from
       * anywhere in the demo tree. */}
      <Toaster />
    </div>
  );
};

export default App;
