// packages/solid/src/components/form/otp/otp.tsx
import {
  type JSX,
  For,
  Show,
  createContext,
  createMemo,
  createSignal,
  mergeProps,
  splitProps,
  useContext,
} from "solid-js";
import { cn } from "../../../lib/cn";
import { arrowStep } from "@algorisys/zen-ui-core";
import "./otp.css";

/**
 * InputOTP — Solid port. One `<input>` per digit, zero dependencies.
 *
 *   <InputOTP value={code()} onValueChange={setCode} maxLength={6} />
 *
 * Custom layout (compound API):
 *
 *   <InputOTP value={code()} onValueChange={setCode} maxLength={6}>
 *     <InputOTPGroup>...</InputOTPGroup>
 *   </InputOTP>
 */

export type InputOTPProps = {
  value?: string;
  defaultValue?: string;
  /** Primary change handler. */
  onValueChange?: (value: string) => void;
  /** @deprecated Use `onValueChange`. */
  onChange?: (value: string) => void;
  onComplete?: (value: string) => void;
  maxLength?: number;
  groupSizes?: number[];
  separator?: JSX.Element;
  children?: JSX.Element;
  class?: string;
  containerClass?: string;
  disabled?: boolean;
  /** Transform pasted text before extracting digits. */
  pasteTransformer?: (text: string) => string;
  /** CSS color for the default slot border. Defaults to `--zen-color-border`. */
  borderColor?: string;
  /** CSS color for the focused slot border. Defaults to `--zen-color-primary`. */
  focusBorderColor?: string;
  /** Extra classes applied to every digit input. */
  slotClass?: string;
};

// --- Context ---------------------------------------------------------------

type OTPContextValue = {
  value: () => string;
  maxLength: () => number;
  disabled: () => boolean | undefined;
  slotClass: () => string | undefined;
  setRef: (index: number, el: HTMLInputElement | null) => void;
  updateValue: (next: string) => void;
  focusInput: (index: number) => void;
  applyDigits: (digits: string) => void;
  sanitize: (raw: string) => string;
};

const OTPContext = createContext<OTPContextValue>();

function useOTPContext() {
  const ctx = useContext(OTPContext);
  if (!ctx) {
    throw new Error("InputOTP subcomponents must be used within <InputOTP>");
  }
  return ctx;
}

function digitsOnly(text: string) {
  return text.replace(/\D/g, "");
}

function sanitizePastedText(
  text: string,
  maxLength: number,
  pasteTransformer?: (text: string) => string,
) {
  const transformed = pasteTransformer ? pasteTransformer(text) : text;
  return digitsOnly(transformed).slice(0, maxLength);
}

const defaultGroupSizes = (maxLength: number): number[] => {
  if (maxLength === 6) return [3, 3];
  if (maxLength === 4) return [4];
  if (maxLength === 5) return [5];
  return [maxLength];
};

// --- The component ---------------------------------------------------------

export const InputOTP = (rawProps: InputOTPProps) => {
  const props = mergeProps({ maxLength: 6, defaultValue: "" }, rawProps);

  const isControlled = () => props.value !== undefined;
  const [uncontrolled, setUncontrolled] = createSignal(props.defaultValue);
  const value = () => (isControlled() ? (props.value as string) : uncontrolled());
  const maxLength = () => props.maxLength;

  const refs: (HTMLInputElement | null)[] = [];
  const setRef = (index: number, el: HTMLInputElement | null) => {
    refs[index] = el;
  };
  const focusInput = (index: number) => {
    const el = refs[index];
    if (el) {
      el.focus();
      el.select();
    }
  };

  const emitChange = (v: string) => (props.onValueChange ?? props.onChange)?.(v);

  const updateValue = (next: string) => {
    const sanitized = digitsOnly(next).slice(0, maxLength());
    if (!isControlled()) setUncontrolled(sanitized);
    emitChange(sanitized);
    if (sanitized.length === maxLength()) props.onComplete?.(sanitized);
  };

  const sanitize = (raw: string) =>
    sanitizePastedText(raw, maxLength(), props.pasteTransformer);

  const applyDigits = (digits: string) => {
    const sanitized = sanitize(digits);
    if (!sanitized) return;
    updateValue(sanitized);
    focusInput(Math.min(sanitized.length, maxLength()) - 1);
  };

  const handleContainerPaste = (e: ClipboardEvent) => {
    if (props.disabled) return;
    const text = e.clipboardData?.getData("text");
    if (!text) return;
    const sanitized = sanitize(text);
    if (!sanitized) return;
    e.preventDefault();
    e.stopPropagation();
    applyDigits(sanitized);
  };

  const style = (): JSX.CSSProperties => ({
    ...(props.borderColor ? { "--zen-otp-slot-border": props.borderColor } : {}),
    ...(props.focusBorderColor
      ? { "--zen-otp-slot-focus-border": props.focusBorderColor }
      : {}),
  });

  const ctx: OTPContextValue = {
    value,
    maxLength,
    disabled: () => props.disabled,
    slotClass: () => props.slotClass,
    setRef,
    updateValue,
    focusInput,
    applyDigits,
    sanitize,
  };

  return (
    <OTPContext.Provider value={ctx}>
      <div
        class={cn(
          "zen-flex zen-items-center zen-gap-2 has-[:disabled]:zen-opacity-50",
          props.containerClass,
          props.class,
        )}
        style={style()}
        onPaste={handleContainerPaste}
      >
        <Show
          when={props.children}
          fallback={
            <DefaultSlots
              maxLength={maxLength()}
              groupSizes={props.groupSizes}
              separator={props.separator}
            />
          }
        >
          {props.children}
        </Show>
      </div>
    </OTPContext.Provider>
  );
};

const DefaultSlots = (props: {
  maxLength: number;
  groupSizes?: number[];
  separator?: JSX.Element;
}) => {
  const groups = createMemo(() => {
    const sizes = props.groupSizes ?? defaultGroupSizes(props.maxLength);
    const out: { start: number; size: number }[] = [];
    let cursor = 0;
    for (const size of sizes) {
      out.push({ start: cursor, size });
      cursor += size;
    }
    return out;
  });

  return (
    <For each={groups()}>
      {(g, gi) => (
        <>
          <Show when={gi() > 0}>
            {props.separator ?? <InputOTPSeparator />}
          </Show>
          <InputOTPGroup>
            <For each={Array.from({ length: g.size }, (_, i) => g.start + i)}>
              {(idx) => <InputOTPSlot index={idx} />}
            </For>
          </InputOTPGroup>
        </>
      )}
    </For>
  );
};

// --- Compound parts --------------------------------------------------------

export type InputOTPGroupProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class" | "children"> & {
  class?: string;
  children?: JSX.Element;
};

export const InputOTPGroup = (props: InputOTPGroupProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <div {...rest} class={cn("zen-flex zen-items-center zen-gap-2", local.class)}>
      {local.children}
    </div>
  );
};

const slotBaseClass = cn(
  "zen-otp-slot zen-h-11 zen-w-11 zen-rounded-zen-md zen-bg-zen-background zen-p-0",
  "zen-text-center zen-text-base zen-font-medium zen-text-zen-foreground zen-tabular-nums",
  "zen-transition-colors",
  "disabled:zen-cursor-not-allowed disabled:zen-opacity-50",
);

// `disabled` is re-declared below only to keep it documented alongside
// `index`; its type is identical to the DOM's, so no Omit is required for it.
export type InputOTPSlotProps = Omit<JSX.InputHTMLAttributes<HTMLInputElement>, "class"> & {
  index: number;
  class?: string;
  disabled?: boolean;
};

export const InputOTPSlot = (rawProps: InputOTPSlotProps) => {
  const [local, rest] = splitProps(rawProps, ["index", "class", "disabled"]);
  const ctx = useOTPContext();
  const char = () => ctx.value()[local.index] ?? "";
  const isDisabled = () => ctx.disabled() || local.disabled;

  const handleInput = (
    e: InputEvent & { currentTarget: HTMLInputElement },
  ) => {
    const digits = ctx.sanitize(e.currentTarget.value);
    const v = ctx.value();
    const i = local.index;
    const max = ctx.maxLength();

    if (digits.length > 1) {
      ctx.applyDigits(digits);
      return;
    }
    if (!digits) {
      ctx.updateValue(v.slice(0, i) + v.slice(i + 1));
      return;
    }
    const next = (v.slice(0, i) + digits + v.slice(i + 1)).slice(0, max);
    ctx.updateValue(next);
    if (i < max - 1) ctx.focusInput(i + 1);
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    const v = ctx.value();
    const i = local.index;

    if (e.key === "Backspace") {
      e.preventDefault();
      if (char()) {
        ctx.updateValue(v.slice(0, i) + v.slice(i + 1));
        return;
      }
      if (i > 0) {
        const prev = i - 1;
        ctx.updateValue(v.slice(0, prev) + v.slice(prev + 1));
        ctx.focusInput(prev);
      }
      return;
    }
    // The boxes sit in a flex row, which reverses in RTL, so the PREVIOUS box
    // is to the right there. Follow the reading direction, not the key name.
    const step = arrowStep(e.key, e.currentTarget as Element);
    if (step === -1 && i > 0) {
      e.preventDefault();
      ctx.focusInput(i - 1);
      return;
    }
    if (step === 1 && i < ctx.maxLength() - 1) {
      e.preventDefault();
      ctx.focusInput(i + 1);
    }
  };

  const handlePaste = (e: ClipboardEvent) => {
    const text = e.clipboardData?.getData("text");
    if (!text) return;
    e.preventDefault();
    ctx.applyDigits(text);
  };

  return (
    <input
      {...rest}
      ref={(el) => ctx.setRef(local.index, el)}
      type="text"
      inputmode="numeric"
      autocomplete={local.index === 0 ? "one-time-code" : "off"}
      aria-label={`Digit ${local.index + 1} of ${ctx.maxLength()}`}
      disabled={isDisabled()}
      value={char()}
      class={cn(slotBaseClass, ctx.slotClass(), local.class)}
      onInput={handleInput}
      onKeyDown={handleKeyDown}
      onPaste={handlePaste}
      onFocus={(e) => e.currentTarget.select()}
    />
  );
};

export type InputOTPSeparatorProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class"> & {
  class?: string;
};

export const InputOTPSeparator = (props: InputOTPSeparatorProps) => {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <div {...rest} role="separator" class={local.class}>
      <DashIcon />
    </div>
  );
};

const DashIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden>
    <line x1="6" y1="12" x2="18" y2="12" />
  </svg>
);

// packages/react/src/components/form/otp/otp.tsx
import * as React from "react";
import { arrowStep } from "@algorisys/zen-ui-core";
import { cn } from "../../../lib/cn";
import "./otp.css";

/**
 * InputOTP — one `<input>` per digit. Drop-in:
 *
 *   <InputOTP value={code} onValueChange={setCode} maxLength={6} />
 *
 * Custom layout (compound API):
 *
 *   <InputOTP value={code} onValueChange={setCode} maxLength={6}>
 *     <InputOTPGroup>...</InputOTPGroup>
 *   </InputOTP>
 */

// --- Props interface (named, single source of truth) -----------------------

export interface InputOTPProps
  extends Omit<
    React.HTMLAttributes<HTMLDivElement>,
    "value" | "defaultValue" | "onChange" | "children"
  > {
  value?: string;
  defaultValue?: string;
  /** Primary change handler. */
  onValueChange?: (value: string) => void;
  /** @deprecated Use `onValueChange`. */
  onChange?: (value: string) => void;
  onComplete?: (value: string) => void;
  maxLength?: number;
  groupSizes?: number[];
  separator?: React.ReactNode;
  children?: React.ReactNode;
  className?: string;
  containerClassName?: string;
  disabled?: boolean;
  /** Transform pasted text before extracting digits. */
  pasteTransformer?: (text: string) => string;
  /**
   * CSS color for the default slot border. Defaults to `--zen-color-border`
   * (theme-aware — visible in dark mode).
   */
  borderColor?: string;
  /**
   * CSS color for the focused slot border. Defaults to `--zen-color-primary`.
   */
  focusBorderColor?: string;
  /** Extra classes applied to every digit input. */
  slotClassName?: string;
}

// --- Context ---------------------------------------------------------------

type OTPContextValue = {
  value: string;
  maxLength: number;
  disabled?: boolean;
  inputRefs: React.MutableRefObject<(HTMLInputElement | null)[]>;
  updateValue: (next: string) => void;
  focusInput: (index: number) => void;
  applyDigits: (digits: string) => void;
  pasteTransformer?: (text: string) => string;
  slotClassName?: string;
};

const OTPInputContext = React.createContext<OTPContextValue | null>(null);

function useOTPContext() {
  const ctx = React.useContext(OTPInputContext);
  if (!ctx) {
    throw new Error("InputOTP subcomponents must be used within <InputOTP>");
  }
  return ctx;
}

function digitsOnly(text: string) {
  return text.replace(/\D/g, "");
}

function sanitizePastedText(
  text: string,
  maxLength: number,
  pasteTransformer?: (text: string) => string,
) {
  const transformed = pasteTransformer ? pasteTransformer(text) : text;
  return digitsOnly(transformed).slice(0, maxLength);
}

// --- Default layout helpers ------------------------------------------------

const defaultGroupSizes = (maxLength: number): number[] => {
  if (maxLength === 6) return [3, 3];
  if (maxLength === 4) return [4];
  if (maxLength === 5) return [5];
  return [maxLength];
};

function renderDefaultSlots(
  maxLength: number,
  groupSizes: number[] | undefined,
  separator: React.ReactNode,
): React.ReactNode {
  const sizes = groupSizes ?? defaultGroupSizes(maxLength);
  const out: React.ReactNode[] = [];
  let cursor = 0;
  sizes.forEach((size, gi) => {
    if (gi > 0) {
      out.push(<React.Fragment key={`sep-${gi}`}>{separator}</React.Fragment>);
    }
    const slots = Array.from({ length: size }, (_, i) => (
      <InputOTPSlot key={cursor + i} index={cursor + i} />
    ));
    out.push(<InputOTPGroup key={`grp-${gi}`}>{slots}</InputOTPGroup>);
    cursor += size;
  });
  return out;
}

// --- The component ---------------------------------------------------------

export const InputOTP = React.forwardRef<HTMLInputElement, InputOTPProps>(
  (
    {
      value: controlledValue,
      defaultValue = "",
      onValueChange,
      onChange,
      onComplete,
      maxLength = 6,
      groupSizes,
      separator = <InputOTPSeparator />,
      children,
      className,
      containerClassName,
      disabled,
      pasteTransformer,
      borderColor,
      focusBorderColor,
      slotClassName,
      style,
      ...rest
    },
    ref,
  ) => {
    const [uncontrolledValue, setUncontrolledValue] = React.useState(defaultValue);
    const isControlled = controlledValue !== undefined;
    const value = isControlled ? controlledValue : uncontrolledValue;
    const inputRefs = React.useRef<(HTMLInputElement | null)[]>([]);
    const valueChangeHandler = onValueChange ?? onChange;

    const updateValue = React.useCallback(
      (next: string) => {
        const sanitized = digitsOnly(next).slice(0, maxLength);
        if (!isControlled) {
          setUncontrolledValue(sanitized);
        }
        valueChangeHandler?.(sanitized);
        if (sanitized.length === maxLength) {
          onComplete?.(sanitized);
        }
      },
      [isControlled, maxLength, valueChangeHandler, onComplete],
    );

    const focusInput = React.useCallback((index: number) => {
      const el = inputRefs.current[index];
      if (el) {
        el.focus();
        el.select();
      }
    }, []);

    const applyDigits = React.useCallback(
      (digits: string) => {
        const sanitized = sanitizePastedText(digits, maxLength, pasteTransformer);
        if (!sanitized) return;
        updateValue(sanitized);
        focusInput(Math.min(sanitized.length, maxLength) - 1);
      },
      [focusInput, maxLength, pasteTransformer, updateValue],
    );

    const handleContainerPaste = React.useCallback(
      (e: React.ClipboardEvent<HTMLDivElement>) => {
        if (disabled) return;
        const text = e.clipboardData.getData("text");
        if (!text) return;
        const sanitized = sanitizePastedText(text, maxLength, pasteTransformer);
        if (!sanitized) return;
        e.preventDefault();
        e.stopPropagation();
        applyDigits(sanitized);
      },
      [applyDigits, disabled, maxLength, pasteTransformer],
    );

    React.useImperativeHandle(ref, () => inputRefs.current[0] as HTMLInputElement);

    const otpStyle = React.useMemo(
      () =>
        ({
          ...(borderColor && { "--zen-otp-slot-border": borderColor }),
          ...(focusBorderColor && { "--zen-otp-slot-focus-border": focusBorderColor }),
        }) as React.CSSProperties,
      [borderColor, focusBorderColor],
    );

    const context = React.useMemo(
      () => ({
        value,
        maxLength,
        disabled,
        inputRefs,
        updateValue,
        focusInput,
        applyDigits,
        pasteTransformer,
        slotClassName,
      }),
      [
        value,
        maxLength,
        disabled,
        updateValue,
        focusInput,
        applyDigits,
        pasteTransformer,
        slotClassName,
      ],
    );

    const content =
      children ?? renderDefaultSlots(maxLength, groupSizes, separator);

    return (
      <OTPInputContext.Provider value={context}>
        <div
          className={cn(
            "zen-flex zen-items-center zen-gap-2 has-[:disabled]:zen-opacity-50",
            containerClassName,
            className,
          )}
          style={{ ...otpStyle, ...style }}
          onPasteCapture={handleContainerPaste}
          {...rest}
        >
          {content}
        </div>
      </OTPInputContext.Provider>
    );
  },
);
InputOTP.displayName = "InputOTP";

// --- Compound parts --------------------------------------------------------

export const InputOTPGroup = React.forwardRef<
  HTMLDivElement,
  React.ComponentPropsWithoutRef<"div">
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("zen-flex zen-items-center zen-gap-2", className)} {...props} />
));
InputOTPGroup.displayName = "InputOTPGroup";

const slotBaseClassName = cn(
  "zen-otp-slot zen-h-11 zen-w-11 zen-rounded-zen-md zen-bg-zen-background zen-p-0",
  "zen-text-center zen-text-base zen-font-medium zen-text-zen-foreground zen-tabular-nums",
  "zen-transition-colors",
  "disabled:zen-cursor-not-allowed disabled:zen-opacity-50",
);

export const InputOTPSlot = React.forwardRef<
  HTMLInputElement,
  Omit<React.ComponentPropsWithoutRef<"input">, "value"> & {
    index: number;
  }
>(
  (
    {
      index,
      className,
      disabled: slotDisabled,
      onChange: onChangeProp,
      onKeyDown: onKeyDownProp,
      onPaste: onPasteProp,
      onFocus: onFocusProp,
      ...props
    },
    ref,
  ) => {
    const {
      value,
      maxLength,
      disabled,
      inputRefs,
      updateValue,
      focusInput,
      applyDigits,
      pasteTransformer,
      slotClassName: contextSlotClassName,
    } = useOTPContext();
    const isDisabled = disabled || slotDisabled;
    const char = value[index] ?? "";

    const setRef = React.useCallback(
      (el: HTMLInputElement | null) => {
        inputRefs.current[index] = el;
        if (typeof ref === "function") {
          ref(el);
        } else if (ref) {
          ref.current = el;
        }
      },
      [index, inputRefs, ref],
    );

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
      onChangeProp?.(e);
      const raw = e.target.value;
      const digits = sanitizePastedText(raw, maxLength, pasteTransformer);

      if (digits.length > 1) {
        applyDigits(digits);
        return;
      }

      if (!digits) {
        updateValue(value.slice(0, index) + value.slice(index + 1));
        return;
      }

      const next = (value.slice(0, index) + digits + value.slice(index + 1)).slice(
        0,
        maxLength,
      );
      updateValue(next);
      if (index < maxLength - 1) {
        focusInput(index + 1);
      }
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
      onKeyDownProp?.(e);
      if (e.defaultPrevented) return;

      if (e.key === "Backspace") {
        e.preventDefault();
        if (char) {
          updateValue(value.slice(0, index) + value.slice(index + 1));
          return;
        }
        if (index > 0) {
          const prev = index - 1;
          updateValue(value.slice(0, prev) + value.slice(prev + 1));
          focusInput(prev);
        }
        return;
      }

      // The boxes sit in a flex row, which reverses in RTL, so the PREVIOUS box
      // is to the right there. Follow the reading direction, not the key name.
      const step = arrowStep(e.key, e.currentTarget);
      if (step === -1 && index > 0) {
        e.preventDefault();
        focusInput(index - 1);
        return;
      }

      if (step === 1 && index < maxLength - 1) {
        e.preventDefault();
        focusInput(index + 1);
      }
    };

    const handlePaste = (e: React.ClipboardEvent<HTMLInputElement>) => {
      onPasteProp?.(e);
      if (e.defaultPrevented) return;
      const text = e.clipboardData.getData("text");
      if (!text) return;
      e.preventDefault();
      applyDigits(text);
    };

    const handleFocus = (e: React.FocusEvent<HTMLInputElement>) => {
      onFocusProp?.(e);
      e.target.select();
    };

    return (
      <input
        ref={setRef}
        type="text"
        inputMode="numeric"
        autoComplete={index === 0 ? "one-time-code" : "off"}
        aria-label={`Digit ${index + 1} of ${maxLength}`}
        disabled={isDisabled}
        value={char}
        className={cn(slotBaseClassName, contextSlotClassName, className)}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        onPaste={handlePaste}
        onFocus={handleFocus}
        {...props}
      />
    );
  },
);
InputOTPSlot.displayName = "InputOTPSlot";

export const InputOTPSeparator = React.forwardRef<
  HTMLDivElement,
  React.ComponentPropsWithoutRef<"div">
>(({ ...props }, ref) => (
  <div ref={ref} role="separator" {...props}>
    <DashIcon />
  </div>
));
InputOTPSeparator.displayName = "InputOTPSeparator";

const DashIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" aria-hidden>
    <line x1="6" y1="12" x2="18" y2="12" />
  </svg>
);
