// packages/solid/src/components/pivot/pivot-workbench.tsx
import { type JSX, createSignal, For, Show, untrack } from "solid-js";
import {
  DragDropProvider,
  DragDropSensors,
  SortableProvider,
  mostIntersecting,
  createSortable,
} from "@thisbeyond/solid-dnd";
import type { CollisionDetector, DragEvent } from "@thisbeyond/solid-dnd";
import { cn } from "../../lib/cn";
import { Button } from "../button/button";
import { Alert, AlertIcon, AlertContent, AlertTitle, AlertDescription } from "../alert/alert";
import { Icon } from "../icon/icon";
import { PivotDropZone } from "./pivot-drop-zone";
import { PivotFieldChip, type PivotFieldChipProps } from "./pivot-field-chip";
import {
  availableFields as availableFieldsIn,
  createEmptyLayout,
  describeMove,
  fieldLabel,
  moveFieldToZone,
  updateValueAggregation,
} from "@algorisys/zen-ui-core/pivot";
import type {
  PivotLayout,
  PivotZone,
  PivotAggregation,
} from "@algorisys/zen-ui-core/pivot";
import type { PivotField, PivotMembersRequest, PivotMembersResult } from "@algorisys/zen-ui-core/pivot";
import type { PivotFilterSelection } from "@algorisys/zen-ui-core/pivot";
export type { PivotField, PivotMembersRequest, PivotMembersResult, PivotFilterSelection };

export interface PivotWorkbenchProps {
  fields: PivotField[];
  initialLayout?: PivotLayout;
  onLayoutApply?: (layout: PivotLayout) => void;
  
  // Custom collision detector or other advanced settings
  class?: string;
  
  // Children to render the grid (passing the applied layout)
  children?: JSX.Element;
  
  // Stats and toolbar
  totalRows?: number;
  totalCols?: number;
  onClearFilters?: () => void;
  
  // Controls visibility of the drag-and-drop builder
  showBuilder?: boolean;

  // Backend callbacks for filter loading
  loadMembers?: (request: PivotMembersRequest) => Promise<PivotMembersResult>;
}

// Custom collision detector that prefers closestCenter for sorting chips,
// but falls back to mostIntersecting for empty zones.
/**
 * Prefer the chip you are over; fall back to the zone you are in.
 *
 * Both halves are load-bearing and the first one was dead: it filters on
 * `d.data.sortable`, which nothing ever set, so `sortableDroppables` was always
 * empty, closestCenter always returned null, and EVERY droppable — zones and
 * chips alike — went to mostIntersecting. That scores by overlap ratio, so a
 * chip-sized target always beat a zone-sized one, and the chip's id (a field
 * key) was then read as a zone name. createSortable marks its data now, so the
 * detector does what it says.
 *
 * Typed against solid-dnd's own CollisionDetector — it exports Draggable,
 * Droppable and this signature, so the four `as any` casts were never needed.
 */
const pivotCollisionDetector: CollisionDetector = (draggable, droppables, context) => {
  // mostIntersecting for BOTH, not closestCenter for the chips.
  //
  // closestCenter returns the nearest candidate whatever the distance — it never
  // returns null while any candidate exists. Over a list of chips that means
  // "some chip, somewhere", so every drop resolved to whichever chip happened to
  // be nearest (usually a neighbour in Available Fields), its zone came back as
  // "available", and the drop was a silent no-op. mostIntersecting requires
  // actual overlap and returns null without it, which is the question being
  // asked: are we ON a chip, or merely in a zone?
  //
  // The dragged chip is excluded because a sortable is its own droppable too:
  // it always overlaps itself, so it would win every time and every drop would
  // resolve to where the field already is.
  const chips = droppables.filter((d) => d.data?.sortable && d.id !== draggable.id);
  const overChip = mostIntersecting(draggable, chips, context);
  if (overChip) return overChip;

  const zones = droppables.filter((d) => !d.data?.sortable);
  return mostIntersecting(draggable, zones, context);
};

const SortableChip = (props: PivotFieldChipProps) => {
  // `sortable: true` is what the collision detector filters on. Without it the
  // detector's chip branch is unreachable and every drop resolves against a
  // zone list that also contains chips.
  const sortable = createSortable(props.fieldKey, { zone: props.zone, sortable: true });
  return (
    <div
      ref={sortable.ref}
      {...sortable.dragActivators}
      // A stable hook for the drag surface, so the shared contract can grab a
      // chip in either binding without depending on a utility class that is an
      // implementation detail.
      data-pivot-chip={fieldLabel(props.fields, props.fieldKey)}
      class={cn(
        "zen-max-w-full zen-touch-none",
        (props.zone === "rows" || props.zone === "values") ? "zen-flex zen-w-full" : "zen-inline-flex",
        sortable.isActiveDraggable && "zen-opacity-50 zen-z-50 zen-relative"
      )}
      style={{
        transform: sortable.transform
          ? `translate3d(${sortable.transform.x}px, ${sortable.transform.y}px, 0)`
          : undefined,
      }}
    >
      <PivotFieldChip {...props} />
    </div>
  );
};

export function PivotWorkbench(props: PivotWorkbenchProps) {
  const [draftLayout, setDraftLayout] = createSignal<PivotLayout>(
    props.initialLayout || createEmptyLayout()
  );
  
  // appliedLayout could be passed to the children if using a render prop,
  // but for this demo, we assume the parent reads it from onLayoutApply.
  const [appliedLayout, setAppliedLayout] = createSignal<PivotLayout>(
    props.initialLayout || createEmptyLayout()
  );

  const availableFields = () => availableFieldsIn(draftLayout(), props.fields);

  /**
   * What a screen reader has just been told. Drag changes the layout silently:
   * to anyone not watching the chips, nothing happened. Both the pointer path
   * and the keyboard path below announce through here, so they cannot diverge.
   */
  const [announcement, setAnnouncement] = createSignal("");

  /**
   * The ONE way a field moves — drag calls it, the chip's menu calls it.
   *
   * Two paths that each did their own layout surgery is how the drag handler
   * ended up deleting fields while the menu did not exist at all.
   */
  const moveField = (fieldId: string, zone: PivotZone, index?: number) => {
    setDraftLayout((prev) => moveFieldToZone(prev, fieldId, zone, { index }));
    setAnnouncement(describeMove(untrack(() => props.fields), fieldId, zone, index));
  };

  const hasAnyFilters = () => {
    const layout = draftLayout();
    if (!layout.filters) return false;
    return Object.keys(layout.filters).length > 0;
  };

  const onDragEnd = (event: DragEvent) => {
    const { draggable, droppable } = event;
    if (!droppable) return;

    const fieldId = draggable.id as string;

    // The zone comes from the droppable's DATA, not from parsing its id.
    //
    // Zones are createDroppable("rows") — id IS the zone, no data. Chips are
    // createSortable(fieldKey, { zone }) — id is a FIELD KEY, and the zone is in
    // the data. Once a zone holds a chip, that chip is the droppable that wins
    // (mostIntersecting scores by overlap ratio, and a chip-sized target beats a
    // zone-sized one), so the old `droppable.id.split("-")[0]` read "country" as
    // a zone, moveFieldToZone hit its `default: return cleanLayout`, and the drop
    // silently removed the field instead of adding it.
    //
    // The effect: the first field into an empty zone worked and every one after
    // it did nothing. A pivot that holds one field per zone is not a pivot.
    const toZone = ((droppable.data?.zone ?? droppable.id) as string) as PivotZone;

    // Dropped ON a chip? Land at that chip's position. Dropped on bare zone?
    // Append. The old code appended in both cases, so a reorder flung the chip
    // to the bottom — and the two functions written to honour a drop index were
    // exported and never called.
    const overFieldId = droppable.data?.zone ? (droppable.id as string) : undefined;
    const index =
      overFieldId && overFieldId !== fieldId ? indexInZone(untrack(draftLayout), overFieldId, toZone) : undefined;

    moveField(fieldId, toZone, index);
  };

  /** Where a field sits inside its zone, or undefined if it is not in one. */
  const indexInZone = (layout: PivotLayout, fieldId: string, zone: PivotZone): number | undefined => {
    const i =
      zone === "rows"
        ? layout.rows.indexOf(fieldId)
        : zone === "columns"
          ? layout.columns.indexOf(fieldId)
          : zone === "values"
            ? layout.values.findIndex((v) => v.id === fieldId)
            : -1;
    return i === -1 ? undefined : i;
  };

  const applyLayout = () => {
    const newLayout = { ...draftLayout() };
    setAppliedLayout(newLayout);
    props.onLayoutApply?.(newLayout);
  };

  const handleAggregationChange = (fieldId: string, agg: PivotAggregation) => {
    setDraftLayout(prev => updateValueAggregation(prev, fieldId, agg));
  };

  const handleRemoveField = (fieldId: string) => moveField(fieldId, "available");

  const handleSelectionChange = (fieldId: string, selection: PivotFilterSelection | null) => {
    setDraftLayout(prev => {
      const filters = { ...prev.filters };
      if (selection) {
        filters[fieldId] = selection;
      } else {
        delete filters[fieldId];
      }
      return { ...prev, filters };
    });
  };

  return (
    <div class={cn("zen-flex zen-flex-col zen-h-full zen-w-full zen-min-h-0 zen-min-w-0 zen-border zen-border-zen-border zen-rounded-zen-md zen-overflow-hidden", props.class)}>
      {/* Every layout change says so out loud. A drag is invisible to a screen
          reader: the chips move and nothing is announced. Polite, so it waits
          for a pause rather than interrupting. */}
      <div aria-live="polite" aria-atomic="true" class="zen-sr-only">
        {announcement()}
      </div>
      <Show 
        when={props.showBuilder !== false}
        fallback={
          <div class="zen-flex-1 zen-min-h-0 zen-min-w-0 zen-relative zen-bg-zen-background">
            <Show when={props.children}>
              {props.children}
            </Show>
          </div>
        }
      >
        <div class="zen-flex zen-flex-col zen-w-full zen-h-full zen-min-h-0 zen-min-w-0 zen-border zen-border-zen-border zen-rounded-md zen-overflow-hidden zen-bg-zen-background">
          <DragDropProvider onDragEnd={onDragEnd} collisionDetector={pivotCollisionDetector}>
            <DragDropSensors>
              <div class="zen-flex zen-flex-col zen-flex-1 zen-w-full zen-h-full zen-min-h-0 zen-min-w-0 zen-text-zen-foreground zen-font-sans">
                {/* Header Section */}
                <div class="zen-border-b zen-border-zen-border zen-bg-zen-muted/30 zen-p-3">
                  <div class="zen-mb-3 zen-flex zen-items-center zen-justify-between">
                    <div class="zen-text-sm zen-font-semibold zen-text-zen-foreground zen-select-none">
                      Available Fields
                    </div>
                    <div class="zen-flex zen-items-center zen-gap-4">
                      <Show when={props.totalRows !== undefined || props.totalCols !== undefined}>
                        <div class="zen-text-xs zen-text-zen-muted-fg zen-leading-relaxed">
                          <div class="zen-flex zen-items-center zen-gap-1.5">
                            <Show when={props.totalRows !== undefined}>
                              <span>
                                <span class="zen-font-medium zen-text-zen-foreground">{props.totalRows?.toLocaleString("en-IN")}</span> rows
                              </span>
                            </Show>
                            <Show when={props.totalRows !== undefined && props.totalCols !== undefined}>
                              <span>&middot;</span>
                            </Show>
                            <Show when={props.totalCols !== undefined}>
                              <span>
                                <span class="zen-font-medium zen-text-zen-foreground">{props.totalCols?.toLocaleString("en-IN")}</span> cols
                              </span>
                            </Show>
                          </div>
                        </div>
                      </Show>
                      <Show when={hasAnyFilters()}>
                        <button
                          type="button"
                          class="zen-text-sm zen-text-zen-muted-fg hover:zen-text-zen-foreground zen-transition-colors zen-p-1 -zen-m-1"
                          onClick={() => {
                            if (props.onClearFilters) {
                              props.onClearFilters();
                            } else {
                              setDraftLayout(prev => ({ ...prev, filters: {} }));
                            }
                          }}
                        >
                          Clear filters
                        </button>
                      </Show>
                      <Button onClick={applyLayout} variant="solid" size="sm">
                        View Data
                      </Button>
                    </div>
                  </div>
                  <PivotDropZone id="available" title="Available Fields" hideTitle horizontal class="zen-border-0 zen-bg-transparent zen-p-0" isEmpty={availableFields().length === 0}>
                    <SortableProvider ids={availableFields().map(f => f.key)}>
                      <For each={availableFields()}>
                        {(field) => (
                          <SortableChip
                            fieldKey={field.key}
                            onMoveToZone={(z: PivotZone) => moveField(field.key, z)}
                            fields={props.fields}
                            zone="available"
                            onRemove={() => handleRemoveField(field.key)}
                            selection={draftLayout().filters?.[field.key]}
                            filters={draftLayout().filters}
                            loadMembers={props.loadMembers}
                            onSelectionChange={(sel: PivotFilterSelection | null) => handleSelectionChange(field.key, sel)}
                            singleSelect={true}
                          />
                        )}
                      </For>
                    </SortableProvider>
                  </PivotDropZone>
                </div>

                {/* Main Content Area */}
                <div class="zen-flex zen-flex-col lg:zen-flex-row zen-flex-1 zen-min-h-0 zen-min-w-0">
                  
                  {/* Sidebar */}
                  <div class="zen-flex zen-flex-col zen-w-full lg:zen-w-64 zen-shrink-0 zen-border-b lg:zen-border-b-0 lg:zen-border-r zen-border-zen-border">
                    <PivotDropZone id="values" title="Values" class="zen-min-h-24 lg:zen-min-h-16" isEmpty={draftLayout().values.length === 0}>
                      <SortableProvider ids={draftLayout().values.map(v => v.id)}>
                        <For each={draftLayout().values}>
                          {(val) => (
                            <SortableChip
                              fieldKey={val.id}
                              onMoveToZone={(z: PivotZone) => moveField(val.id, z)}
                              fields={props.fields}
                              zone="values"
                              aggregation={val.aggregation}
                              onAggregationChange={(agg: PivotAggregation) => handleAggregationChange(val.id, agg)}
                              onRemove={() => handleRemoveField(val.id)}
                              selection={draftLayout().filters?.[val.id]}
                              filters={draftLayout().filters}
                              loadMembers={props.loadMembers}
                              onSelectionChange={(sel: PivotFilterSelection | null) => handleSelectionChange(val.id, sel)}
                            />
                          )}
                        </For>
                      </SortableProvider>
                    </PivotDropZone>
                    <PivotDropZone id="rows" title="Rows" class="zen-flex-1 zen-min-h-24 lg:zen-min-h-16 zen-border-t zen-border-zen-border" isEmpty={draftLayout().rows.length === 0}>
                      <SortableProvider ids={draftLayout().rows}>
                        <For each={draftLayout().rows}>
                          {(fieldId) => {
                            return (
                              <SortableChip
                                fieldKey={fieldId}
                                onMoveToZone={(z: PivotZone) => moveField(fieldId, z)}
                                fields={props.fields}
                                zone="rows"
                                onRemove={() => handleRemoveField(fieldId)}
                                selection={draftLayout().filters?.[fieldId]}
                                filters={draftLayout().filters}
                                loadMembers={props.loadMembers}
                                onSelectionChange={(sel: PivotFilterSelection | null) => handleSelectionChange(fieldId, sel)}
                              />
                            );
                          }}
                        </For>
                      </SortableProvider>
                    </PivotDropZone>
                  </div>

                  {/* Grid Area */}
                  <div class="zen-flex zen-flex-col zen-flex-1 zen-min-w-0 zen-min-h-0">
                    <PivotDropZone id="columns" title="Columns" horizontal class="zen-bg-zen-muted/10 zen-border-b zen-border-zen-border zen-shrink-0 zen-min-h-16" isEmpty={draftLayout().columns.length === 0}>
                      <SortableProvider ids={draftLayout().columns}>
                        <For each={draftLayout().columns}>
                          {(fieldId) => {
                            return (
                              <SortableChip
                                fieldKey={fieldId}
                                onMoveToZone={(z: PivotZone) => moveField(fieldId, z)}
                                fields={props.fields}
                                zone="columns"
                                onRemove={() => handleRemoveField(fieldId)}
                                selection={draftLayout().filters?.[fieldId]}
                                filters={draftLayout().filters}
                                loadMembers={props.loadMembers}
                                onSelectionChange={(sel: PivotFilterSelection | null) => handleSelectionChange(fieldId, sel)}
                              />
                            );
                          }}
                        </For>
                      </SortableProvider>
                    </PivotDropZone>
                    <div class="zen-flex-1 zen-relative zen-bg-zen-background lg:zen-h-[500px] zen-h-[350px] zen-min-h-0 zen-min-w-0">
                      <Show when={appliedLayout().values.length === 0 || (appliedLayout().rows.length === 0 && appliedLayout().columns.length === 0)}>
                        <div class="zen-p-4 zen-flex zen-flex-col zen-gap-2">
                          <Show when={appliedLayout().values.length === 0}>
                            <Alert color="warning" variant="soft">
                               <AlertIcon><Icon name="info" /></AlertIcon>
                               <AlertContent>
                                 <AlertTitle>Value field required</AlertTitle>
                                 <AlertDescription>Please drop at least one field into the Values section to calculate data.</AlertDescription>
                               </AlertContent>
                            </Alert>
                          </Show>
                          <Show when={appliedLayout().rows.length === 0 && appliedLayout().columns.length === 0}>
                            <Alert color="warning" variant="soft">
                               <AlertIcon><Icon name="info" /></AlertIcon>
                               <AlertContent>
                                 <AlertTitle>Dimension required</AlertTitle>
                                 <AlertDescription>Please drop at least one field into the Rows or Columns section.</AlertDescription>
                               </AlertContent>
                            </Alert>
                          </Show>
                        </div>
                      </Show>
                      
                      <Show when={appliedLayout().values.length > 0 && (appliedLayout().rows.length > 0 || appliedLayout().columns.length > 0)}>
                        <div class="zen-absolute zen-inset-0">
                          <Show when={props.children}>
                            {props.children}
                          </Show>
                        </div>
                      </Show>
                    </div>
                  </div>
                </div>
              </div>
            </DragDropSensors>
          </DragDropProvider>
        </div>
      </Show>
    </div>
  );
}

// packages/react/src/components/pivot/pivot-workbench.tsx
import * as React from "react";
import {
  DndContext,
  PointerSensor,
  pointerWithin,
  useSensor,
  useSensors,
  type CollisionDetection,
  type DragEndEvent,
} from "@dnd-kit/core";
import { useSortable } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import {
  availableFields as availableFieldsIn,
  createEmptyLayout,
  describeMove,
  fieldLabel,
  hasActiveFilters,
  isLayoutRenderable,
  moveFieldToZone,
  updateValueAggregation,
  type PivotField,
  type PivotFilterSelection,
  type PivotLayout,
  type PivotMembersRequest,
  type PivotMembersResult,
  type PivotZone,
} from "@algorisys/zen-ui-core/pivot";
import { cn } from "../../lib/cn";
import { Alert, AlertContent, AlertDescription, AlertIcon, AlertTitle } from "../alert/alert";
import { Button } from "../button/button";
import { PivotDropZone } from "./pivot-drop-zone";
import { PivotFieldChip, type PivotFieldChipProps } from "./pivot-field-chip";

/**
 * PivotWorkbench — drag fields into zones, press View Data, get a layout.
 *
 * Mirrors the Solid binding's API exactly. Every layout rule comes from
 * @algorisys/zen-ui-core/pivot, so the two bindings cannot disagree about what a
 * drop means — which matters here more than anywhere, because they share no drag
 * library: @dnd-kit here, @thisbeyond/solid-dnd there.
 *
 * It computes nothing and holds no data. You get a PivotLayout; answering for
 * the cells is yours.
 */

export interface PivotWorkbenchProps {
  fields: PivotField[];
  initialLayout?: PivotLayout;
  /** Fires on "View Data", not on every drag. */
  onLayoutApply?: (layout: PivotLayout) => void;
  className?: string;
  /** The grid. Rendered, never talked to. */
  children?: React.ReactNode;
  totalRows?: number;
  totalCols?: number;
  onClearFilters?: () => void;
  showBuilder?: boolean;
  loadMembers?: (request: PivotMembersRequest) => Promise<PivotMembersResult>;
}

/** A chip that can be dragged. The chip itself knows nothing about dragging. */
const SortableChip: React.FC<PivotFieldChipProps> = (props) => {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useSortable({
    id: props.fieldKey,
    // `zone` is what the drop handler reads. It must never parse the zone out of
    // a droppable's id: once a zone holds a chip, the CHIP is the droppable that
    // wins, and its id is a field key. Reading an id as a zone is what deleted
    // fields.
    data: { zone: props.zone, sortable: true },
  });

  return (
    <div
      ref={setNodeRef}
      {...attributes}
      {...listeners}
      data-pivot-chip={fieldLabel(props.fields, props.fieldKey)}
      style={{ transform: CSS.Translate.toString(transform) }}
      className={cn(
        "zen-max-w-full zen-touch-none",
        props.zone === "rows" || props.zone === "values" ? "zen-flex zen-w-full" : "zen-inline-flex",
        isDragging && "zen-relative zen-z-50 zen-opacity-50",
      )}
    >
      <PivotFieldChip {...props} />
    </div>
  );
};

/**
 * Prefer the chip you are over; fall back to the zone you are in.
 *
 * pointerWithin, not closestCenter: closestCenter returns the nearest candidate
 * at ANY distance and never returns null while one exists, so over a list of
 * chips it means "some chip, somewhere" — every drop would resolve to whichever
 * chip happened to be closest, usually one still sitting in Available Fields.
 * pointerWithin asks the question actually being asked: is the pointer ON a chip,
 * or merely in a zone?
 *
 * The dragged chip is excluded because a sortable is its own droppable: it always
 * contains its own pointer, so it would win every time.
 */
const pivotCollisionDetection: CollisionDetection = (args) => {
  const chips = args.droppableContainers.filter(
    (d) => d.data.current?.sortable && d.id !== args.active.id,
  );
  const overChip = pointerWithin({ ...args, droppableContainers: chips });
  if (overChip.length) return overChip;

  const zones = args.droppableContainers.filter((d) => !d.data.current?.sortable);
  return pointerWithin({ ...args, droppableContainers: zones });
};

export const PivotWorkbench: React.FC<PivotWorkbenchProps> = ({
  fields,
  initialLayout,
  onLayoutApply,
  className,
  children,
  totalRows,
  totalCols,
  onClearFilters,
  showBuilder = true,
  loadMembers,
}) => {
  // Draft vs applied: dragging edits the draft, View Data publishes it. Same
  // split the List Report makes between its filter bar and its table, for the
  // same reason — re-querying a pivot on every drag is fine over 48 rows and
  // hostile over 48 million.
  const [draft, setDraft] = React.useState<PivotLayout>(initialLayout ?? createEmptyLayout());
  const [applied, setApplied] = React.useState<PivotLayout>(initialLayout ?? createEmptyLayout());

  /** What a screen reader has just been told. A drag is otherwise silent. */
  const [announcement, setAnnouncement] = React.useState("");

  const sensors = useSensors(
    // A small distance, so a click on the ⋮ handle or the remove button is not
    // read as the start of a drag.
    useSensor(PointerSensor, { activationConstraint: { distance: 5 } }),
  );

  /** The ONE way a field moves — drag calls it, the chip's menu calls it. */
  const moveField = React.useCallback(
    (fieldId: string, zone: PivotZone, index?: number) => {
      setDraft((prev) => moveFieldToZone(prev, fieldId, zone, { index }));
      setAnnouncement(describeMove(fields, fieldId, zone, index));
    },
    [fields],
  );

  const onDragEnd = (event: DragEndEvent) => {
    const { active, over } = event;
    if (!over) return;
    const fieldId = String(active.id);

    // From the droppable's DATA, never from parsing its id.
    const zone = (over.data.current?.zone ?? over.id) as PivotZone;
    const overIsChip = Boolean(over.data.current?.sortable);
    const index = overIsChip ? indexInZone(draft, String(over.id), zone) : undefined;
    moveField(fieldId, zone, index);
  };

  const available = availableFieldsIn(draft, fields);
  const renderable = isLayoutRenderable(applied);

  const chipProps = (fieldKey: string, zone: PivotZone): PivotFieldChipProps => ({
    fieldKey,
    fields,
    zone,
    filters: draft.filters,
    selection: draft.filters[fieldKey],
    loadMembers,
    onSelectionChange: (sel) => setDraft((prev) => withFilter(prev, fieldKey, sel)),
    onMoveToZone: (z) => moveField(fieldKey, z),
    onRemove: zone === "available" ? undefined : () => moveField(fieldKey, "available"),
  });

  return (
    <div
      className={cn(
        "zen-flex zen-h-full zen-w-full zen-min-w-0 zen-flex-col zen-overflow-hidden zen-rounded-zen-md zen-border zen-border-zen-border",
        className,
      )}
    >
      {/* Every layout change says so out loud. */}
      <div aria-live="polite" aria-atomic="true" className="zen-sr-only">
        {announcement}
      </div>

      <DndContext sensors={sensors} collisionDetection={pivotCollisionDetection} onDragEnd={onDragEnd}>
        <div className="zen-flex zen-w-full zen-flex-col zen-gap-2 zen-bg-zen-background zen-p-2">
          {showBuilder ? (
            <>
              <div className="zen-flex zen-items-center zen-justify-between zen-gap-2">
                <span className="zen-text-xs zen-text-zen-muted-fg">
                  {(totalRows ?? 0).toLocaleString()} rows · {(totalCols ?? 0).toLocaleString()} cols
                </span>
                <div className="zen-flex zen-items-center zen-gap-2">
                  {hasActiveFilters(draft.filters) ? (
                    <button
                      type="button"
                      className="-zen-m-1 zen-cursor-pointer zen-border-0 zen-bg-transparent zen-p-1 zen-text-sm zen-text-zen-muted-fg hover:zen-text-zen-foreground"
                      onClick={() => {
                        if (onClearFilters) onClearFilters();
                        else setDraft((prev) => ({ ...prev, filters: {} }));
                      }}
                    >
                      Clear filters
                    </button>
                  ) : null}
                  <Button
                    size="sm"
                    onClick={() => {
                      setApplied(draft);
                      onLayoutApply?.(draft);
                    }}
                  >
                    View Data
                  </Button>
                </div>
              </div>

              <PivotDropZone
                id="available"
                title="Available Fields"
                horizontal
                isEmpty={available.length === 0}
              >
                {available.map((f) => (
                  <SortableChip key={f.key} {...chipProps(f.key, "available")} />
                ))}
              </PivotDropZone>

              <div className="zen-grid zen-grid-cols-1 zen-gap-2 sm:zen-grid-cols-3">
                <PivotDropZone id="values" title="Values" isEmpty={draft.values.length === 0}>
                  {draft.values.map((v) => (
                    <SortableChip
                      key={v.id}
                      {...chipProps(v.id, "values")}
                      aggregation={v.aggregation}
                      onAggregationChange={(agg) => setDraft((prev) => updateValueAggregation(prev, v.id, agg))}
                    />
                  ))}
                </PivotDropZone>

                <PivotDropZone id="rows" title="Rows" isEmpty={draft.rows.length === 0}>
                  {draft.rows.map((id) => (
                    <SortableChip key={id} {...chipProps(id, "rows")} />
                  ))}
                </PivotDropZone>

                <PivotDropZone id="columns" title="Columns" isEmpty={draft.columns.length === 0}>
                  {draft.columns.map((id) => (
                    <SortableChip key={id} {...chipProps(id, "columns")} />
                  ))}
                </PivotDropZone>
              </div>
            </>
          ) : null}
        </div>
      </DndContext>

      <div className="zen-relative zen-min-h-0 zen-min-w-0 zen-flex-1 zen-bg-zen-background zen-p-2">
        {renderable ? (
          children
        ) : (
          <div className="zen-flex zen-flex-col zen-gap-2">
            {applied.values.length === 0 ? (
              <Alert color="warning">
                <AlertIcon />
                <AlertContent>
                  <AlertTitle>Value field required</AlertTitle>
                  <AlertDescription>Drop at least one field into Values to calculate data.</AlertDescription>
                </AlertContent>
              </Alert>
            ) : null}
            {applied.rows.length === 0 && applied.columns.length === 0 ? (
              <Alert color="warning">
                <AlertIcon />
                <AlertContent>
                  <AlertTitle>Dimension required</AlertTitle>
                  <AlertDescription>Drop at least one field into Rows or Columns.</AlertDescription>
                </AlertContent>
              </Alert>
            ) : null}
          </div>
        )}
      </div>
    </div>
  );
};
PivotWorkbench.displayName = "PivotWorkbench";

/** Where a field sits inside its zone, or undefined if it is not in one. */
const indexInZone = (layout: PivotLayout, fieldId: string, zone: PivotZone): number | undefined => {
  const i =
    zone === "rows"
      ? layout.rows.indexOf(fieldId)
      : zone === "columns"
        ? layout.columns.indexOf(fieldId)
        : zone === "values"
          ? layout.values.findIndex((v) => v.id === fieldId)
          : -1;
  return i === -1 ? undefined : i;
};

/** Set or clear one field's filter. */
const withFilter = (layout: PivotLayout, fieldKey: string, sel: PivotFilterSelection | null): PivotLayout => {
  const filters = { ...layout.filters };
  if (sel) filters[fieldKey] = sel;
  else delete filters[fieldKey];
  return { ...layout, filters };
};
